libgeos/geos

- CMakeLists.txt
- autogen.bat
- capi/CMakeLists.txt
- tools/geos_revision_cmake.h.in
Remove `tools/geos_revision_cmake.h.in` as no longer required - `geos_revision.h` is generated on-fly.
Add `geos_revision` target set as dependency of `geos_c` target.
> [CMake] Simplify generation of geos_revision.h

- Makefile.am
Allow to compile geos source tarball using cmake.
See discussion here: https://trac.osgeo.org/geos/ticket/753#comment:22
> ENH: add GenerateSourceGroups.cmake to EXTRA_DIST

- src/geom/CoordinateArraySequence.cpp
- src/geomgraph/EdgeEndStar.cpp
- src/operation/buffer/SubgraphDepthLocater.cpp
- src/operation/linemerge/LineSequencer.cpp
- src/operation/overlay/LineBuilder.cpp
clang-tidy: readability-container-size-empty size() == 0 can be replaced with empty()
​https://clang.llvm.org/extra/clang-tidy/checks/readability-container-size-empty.html
> size() == 0 -> empty() (#849)

- capi/geos_c.h.in
Documented return codes don't match implementation:
https://github.com/libgeos/geos/blob/a71f21a9d36e483628e7d2c46fb9d24dfcec98bc/capi/geos_ts_c.cpp#L3115-L3156
> Fixed documented return codes of GEOSGeomGetX() and friends.

- src/algorithm/CGAlgorithms.cpp
- tests/unit/capi/GEOSCoordSeqTest.cpp
https://trac.osgeo.org/geos/ticket/927
> Fix #927 -- Fixed crash in GEOSCoordSeq_isCCW() when used with empty coordseq.

- src/operation/union/UnaryUnionOp.cpp
- tests/unit/capi/GEOSUnaryUnionTest.cpp
- tests/unit/operation/union/UnaryUnionOpTest.cpp
https://trac.osgeo.org/geos/ticket/928
> Fix #928: Fixed crash in GEOSUnaryUnion() when used with empty linestring.

- capi/geos_ts_c.cpp
In some cases, the CAPI function `GEOSLength_r` returns `2` on error, when it is documented to return `0`. The `2` is likely to be interpreted as "success" by a caller.
In some cases, the CAPI function `GEOSIsValidDetail_r` returns `0` on error, when it is documented to return `2`. The `0` would be falsely interpreted as "geometry invalid."
Trac ticket https://trac.osgeo.org/geos/ticket/941#ticket
> Fix incorrect error return values in CAPI

- include/geos/algorithm/MCPointInRing.h
- include/geos/index/chain/MonotoneChainBuilder.h
- include/geos/noding/MCIndexSegmentSetMutualIntersector.h
- src/algorithm/MCPointInRing.cpp
- src/index/bintree/NodeBase.cpp
- src/index/chain/MonotoneChainBuilder.cpp
- src/noding/MCIndexNoder.cpp
- src/noding/MCIndexSegmentSetMutualIntersector.cpp
https://trac.osgeo.org/geos/ticket/912#comment:1
This PR takes things a bit farther than needed to strictly fix the bug, by using std::unique_ptr to clearly define the ownership of objects returned by MonotoneChainBuilder.
> Resolve segfault in BinTree

- src/geom/GeometryCollection.cpp
- tests/unit/Makefile.am
- tests/unit/geom/GeometryCollectionTest.cpp
https://trac.osgeo.org/geos/ticket/947
> Fix #947: Fix getCoordinate() of non-empty collection with empty first item.

- include/geos/geom/GeometryCollection.h
- src/geom/GeometryCollection.cpp
- src/io/WKBWriter.cpp
- tests/unit/Makefile.am
- tests/unit/geom/GeometryCollectionTest.cpp
https://trac.osgeo.org/geos/ticket/924
> Fix #924: Geometries returned by getGeometryN() now have the same SRID as collection.

- NEWS
- capi/geos_c.cpp
- capi/geos_c.h.in
- capi/geos_ts_c.cpp
- include/geos/operation/polygonize/BuildArea.h
- include/geos/operation/polygonize/Makefile.am
- include/geos/operation/valid/MakeValid.h
- src/operation/polygonize/BuildArea.cpp
- src/operation/polygonize/Makefile.am
- src/operation/valid/MakeValid.cpp
- src/operation/valid/Makefile.am
- tests/unit/Makefile.am
- tests/unit/capi/GEOSBuildArea.cpp
- tests/unit/capi/GEOSMakeValid.cpp
- tests/xmltester/CMakeLists.txt
- tests/xmltester/Makefile.am
- tests/xmltester/XMLTester.cpp
- tests/xmltester/tests/buildarea.xml
- tests/xmltester/tests/makevalid.xml
See https://trac.osgeo.org/geos/ticket/952
This is a proper C++ port of the librttopo code, originally using GEOS C API.
> Add PolygonizerExcludeHoles and MakeValid operations (fixes #952)

- .travis.yml
- CMakeLists.txt
This PR reduces the CMake version requirement with Visual Studio builds to 3.13, which is the version currently installed on AppVeyor.
> Reduce CMake version requirement

- .travis.yml
There is no need to test each compiler/architecture combination using
both build systems. This commit uses CMake as the primary build system
for Travis (since it is significantly faster) and includes one autotools
build for a single compiler/architecture to verify that the autotools
system can continue to be used.
> Reduce travis matrix

- CMakeLists.txt
This is required to trigger generation of `.lib` archive with import library for DLL.
-----
This may hit some aspect of the cause of AppVeyor failures.
> Add GEOS_DLL_EXPORT to compile definitions for MSVC

- include/geos/geom/CoordinateArraySequence.h
- include/geos/geom/CoordinateSequence.h
- src/geom/CoordinateArraySequence.cpp
- src/geom/LinearRing.cpp
- src/operation/overlay/snap/GeometrySnapper.cpp
- src/operation/overlay/validate/OverlayResultValidator.cpp
- src/simplify/DouglasPeuckerSimplifier.cpp
Deprecated a decade ago, but still used a couple of times within GEOS.
Supports the goal of a smaller CoordinateSequence interface.
> Remove CoordinateSequence::toVector()

- tests/unit/tut/tut.hpp
This is to avoid flood of 100+ occurrences of the warning.
> Fix MSVC warning C4189: local variable not referenced

- CMakeLists.txt
Place executables and shared libraries in the same location for
convenience of direct execution from common spot and for
convenience in environments without `RPATH` support.
In future, if number of generated executables grows significantly,
with possible name clashes, it may be more convenient to replace
the common locations with setting `PATH` per test, on Windows only:
```
set_tests_properties(<test name> PROPERTIES
ENVIRONMENT
"PATH=$<SHELL_PATH:$<TARGET_FILE_DIR:geos>>$<SEMICOLON>$<TARGET_FILE_DIR:geos_c>>$<SEMICOLON>$ENV{PATH}"
)
```
----
@robe2 this should fix the test issues on Windows
> Point CMAKE_*_OUTPUT_DIRECTORY to common location

- .azure-pipelines.yml
This AzP provides comprehensive setup for CI builds:
- on Linux, MacOS, Windows
- compiling with
- clang 3.5 - 8
- GCC 4.9 - 8
- Visual Studio 2017, 2015, 2019
- Xcode 8.3.3 to 10.1
- targeting C++ standard versions: 11, 14, 17, 20 (2a)
- configuring with CMake 3.12.4 (Linux), 3.14.3 (MacOS), 3.14.4 (Windows)
- with CMAKE_BUILD_TYPE=Release
This configuration allows any contributor to set up CI pipelines with AzP at `https://dev.azure.com/<owner>/geos` and build directly from GitHub upstream (libgeos/geos) or own fork in order to test own topic branches as well the master.
-----
/cc @dbaston 
Sample build matrix available at https://dev.azure.com/mloskot/geos/_build/
> Add Azure Pipelines configuration for CI builds using CMake

- CMakeLists.txt
- doc/CMakeLists.txt
Important to make sure example still compiles after C++ API changes.
Resolves #901.
> [CMake] Add target for doc/example.cpp

- benchmarks/algorithm/CMakeLists.txt
- benchmarks/algorithm/VoronoiPerfTest.cpp
- include/geos/triangulate/DelaunayTriangulationBuilder.h
- include/geos/triangulate/IncrementalDelaunayTriangulator.h
- include/geos/triangulate/VoronoiDiagramBuilder.h
- include/geos/triangulate/quadedge/QuadEdgeSubdivision.h
- src/triangulate/DelaunayTriangulationBuilder.cpp
- src/triangulate/IncrementalDelaunayTriangulator.cpp
- src/triangulate/VoronoiDiagramBuilder.cpp
- src/triangulate/quadedge/QuadEdgeSubdivision.cpp
- tests/unit/triangulate/quadedge/QuadEdgeSubdivisionTest.cpp
Improve performance of VoronoiDiagramBuilder and DelaunayTriangulationBuilder.
Overall performance improvement is about 20-30% using a benchmark of 100,000
random points. Improvements picked up a few percent at a time, via:
- Reducing manual memory allocation
- Removing some unnecessary copying
- Using unordered_set instead of set
- etc.
There may be some room for improvement in the `QuadEdgeSubdivision` structure itself; I'm not familiar enough with that to make many changes.
> Optimize Voronoi / Delaunay code

- capi/geos_ts_c.cpp
- include/geos/geom/LineSegment.h
- include/geos/geom/LineSegment.inl
- include/geos/operation/distance/ConnectedElementLocationFilter.h
- include/geos/operation/distance/DistanceOp.h
- src/geom/LineSegment.cpp
- src/operation/distance/ConnectedElementLocationFilter.cpp
- src/operation/distance/DistanceOp.cpp
- src/operation/distance/FacetSequence.cpp
- tests/unit/operation/distance/DistanceOpTest.cpp
This PR takes a fairly invasive approach to resolving the leaks
and removes all manual memory management from the DistanceOp class.
It also removes some deprecated methods and replaces fixed-size std::vectors
with std::array.
> Resolve memory leaks in DistanceOp

- include/geos/util.h
- src/algorithm/locate/IndexedPointInAreaLocator.cpp
- src/geom/CoordinateArraySequence.cpp
- src/geom/GeometryFactory.cpp
- src/geomgraph/PlanarGraph.cpp
- src/operation/overlay/snap/GeometrySnapper.cpp
- src/operation/valid/RepeatedPointRemover.cpp
- src/triangulate/DelaunayTriangulationBuilder.cpp
- src/triangulate/VoronoiDiagramBuilder.cpp
- src/triangulate/quadedge/QuadEdgeSubdivision.cpp
- src/triangulate/quadedge/Vertex.cpp
This PR "backports" the `std::make_unique` function from C++14 to the `geos_util.h` header and applies it to a portion of the locations where it makes sense. `make_unique`, which I copied from QGIS (in turn copied from Stack Overflow) lets us replace this syntax:
`auto a = std::unique_ptr<std::vector<const Geometry*>>(new std::vector<const Geometry*>(5));`
with this syntax:
`auto a = make_unique<std::vector<const Geometry*>>(5);`
So there is a bit of a win in avoiding writing long type names two times. It also avoids the potential for a memory leak if one of the arguments to the `std::unique_ptr` construction throws; see https://stackoverflow.com/a/19472607 or Effective Modern C++
If people are OK with adding `make_unique` to our own header, I can make the rest of the conversions. I think …
> Add make_unique to geos_util.h

- include/geos/geom/CoordinateArraySequence.h
- include/geos/geom/CoordinateSequence.h
- src/geom/CoordinateArraySequence.cpp
- src/geom/CoordinateSequence.cpp
Instead of being a pure virtual function that all implementations must
provide, CoordinateSequence::toString() now uses the existing ostream
operator to provide a consistent string representation for any
CoordinateSequence.
> Implement CoordinateSequence::toString()

- doc/example.cpp
- include/geos/geom/CoordinateArraySequence.h
- include/geos/geom/CoordinateSequence.h
- include/geos/geomgraph/EdgeRing.h
- include/geos/linearref/LinearGeometryBuilder.h
- include/geos/noding/SegmentIntersectionDetector.h
- include/geos/operation/linemerge/EdgeString.h
- include/geos/operation/polygonize/EdgeRing.h
- include/geos/operation/valid/RepeatedPointRemover.h
- src/algorithm/MinimumBoundingCircle.cpp
- src/algorithm/MinimumDiameter.cpp
- src/geom/CoordinateArraySequence.cpp
- src/geom/CoordinateSequence.cpp
- src/geom/GeometryFactory.cpp
- src/geom/LineSegment.cpp
- src/geom/Polygon.cpp
- src/geomgraph/EdgeRing.cpp
- src/io/WKTReader.cpp
- src/operation/buffer/BufferInputLineSimplifier.cpp
- src/operation/linemerge/EdgeString.cpp
- src/operation/polygonize/EdgeRing.cpp
- src/operation/valid/RepeatedPointRemover.cpp
- src/triangulate/quadedge/QuadEdgeSubdivision.cpp
- tests/bigtest/GeometryTestFactory.cpp
- tests/unit/algorithm/RobustLineIntersectorTest.cpp
- tests/unit/geom/PointTest.cpp
- tests/unit/noding/BasicSegmentStringTest.cpp
- tests/unit/noding/NodedSegmentStringTest.cpp
- tests/unit/noding/SegmentNodeTest.cpp
- tests/unit/operation/valid/IsValidTest.cpp
Making this change removes the assumption that any CoordinateSequence is
resizable, which opens the door to a CoordinateSequence that is blocked
by a raw block of memory (such as a PostGIS POINTARRAY).
The default CoordinateArraySequence constructor now creates a
CoordinateSequence of unknown dimension (dimension determined when the
first Coordinate is assigned) rather than of dimension 3. This is for
consistency with the behavior of the CoordinateArraySequenceFactory.
> Move CoordinateSequence::add variants to CoordinateArraySequence

- benchmarks/capi/CMakeLists.txt
- benchmarks/capi/GEOSPreparedContainsPerfTest.cpp
- include/geos/algorithm/RayCrossingCounter.h
- include/geos/geom/GeometryComponentFilter.h
- include/geos/geom/prep/AbstractPreparedPolygonContains.h
- include/geos/geom/prep/PreparedPolygonPredicate.h
- src/algorithm/RayCrossingCounter.cpp
- src/geom/GeometryCollection.cpp
- src/geom/Polygon.cpp
- src/geom/prep/AbstractPreparedPolygonContains.cpp
- src/geom/prep/BasicPreparedGeometry.cpp
- src/geom/prep/PreparedPolygonPredicate.cpp
- tests/unit/geom/GeometryComponentFilterTest.cpp
- tests/xmltester/tests/general/TestPreparedPolygonPredicate.xml
This PR improves the performance of GEOSPreparedContains by about 30% for point inputs and adds some benchmarking code to the repository.
@dr-jts some of the tweaks here may be relevant for JTS. They're probably most easily reviewed in the individual commits, rather than by the whole PR diff.
> GEOSPreparedContains performance improvements

- capi/geos_ts_c.cpp
- doc/example.cpp
- include/geos/geom/Geometry.h
- include/geos/geom/GeometryFactory.h
- include/geos/geom/Polygon.h
- include/geos/operation/polygonize/EdgeRing.h
- src/algorithm/InteriorPointArea.cpp
- src/algorithm/PointLocator.cpp
- src/geom/Geometry.cpp
- src/geom/GeometryFactory.cpp
- src/geom/Polygon.cpp
- src/geom/util/GeometryEditor.cpp
- src/geom/util/GeometryTransformer.cpp
- src/geomgraph/EdgeRing.cpp
- src/geomgraph/GeometryGraph.cpp
- src/io/WKBReader.cpp
- src/io/WKTReader.cpp
- src/operation/buffer/OffsetCurveSetBuilder.cpp
- src/operation/intersection/RectangleIntersection.cpp
- src/operation/intersection/RectangleIntersectionBuilder.cpp
- src/operation/polygonize/EdgeRing.cpp
- src/operation/valid/IsValidOp.cpp
- tests/unit/geom/GeometryFactoryTest.cpp
This removes the need for numerous dynamic casts.
Related:
JTS 992948a3312be5ad9bf97fc50b3c3a0de3acece1
JTS af8aee0ba345d5f5f8c845c721d9df20fac3bd3d
> Handle Polygon rings as LinearRings

- include/geos/geom/util/CoordinateOperation.h
- include/geos/geom/util/GeometryCombiner.h
- include/geos/geom/util/GeometryEditor.h
- include/geos/geom/util/GeometryEditorOperation.h
- include/geos/precision/PrecisionReducerCoordinateOperation.h
- include/geos/precision/SimpleGeometryPrecisionReducer.h
- src/geom/GeometryFactory.cpp
- src/geom/util/CoordinateOperation.cpp
- src/geom/util/GeometryCombiner.cpp
- src/geom/util/GeometryEditor.cpp
- src/operation/union/CascadedPolygonUnion.cpp
- src/operation/union/CascadedUnion.cpp
- src/precision/GeometryPrecisionReducer.cpp
- src/precision/PrecisionReducerCoordinateOperation.cpp
- src/precision/SimpleGeometryPrecisionReducer.cpp
This PR updates `GeometryEditor` and associated classes to use `std::unique_ptr`.
> Use unique_ptr in GeometryEditor

- include/geos/geom/Geometry.h
- include/geos/geom/GeometryCollection.h
- include/geos/geom/GeometryCollection.inl
- include/geos/geom/Polygon.h
- src/algorithm/PointLocator.cpp
- src/algorithm/locate/SimplePointInAreaLocator.cpp
- src/geom/Geometry.cpp
- src/geom/GeometryCollection.cpp
- src/geom/MultiLineString.cpp
- src/geom/MultiPoint.cpp
- src/geom/MultiPolygon.cpp
- src/geom/Polygon.cpp
- src/operation/IsSimpleOp.cpp
- src/operation/union/CascadedPolygonUnion.cpp
- src/operation/valid/MakeValid.cpp
This PR updates `GeometryCollection` and `Polygon` to manage their
components using a std::vector of std::unique_ptr. It also avoids
heap-allocating the std::vectors themselves.
An improvement I can think of is to have `GeometryColleciton::begin`
iterate over the raw pointers themselves instead of the `unique_ptr`.
This avoids `GeometryCollection` users needing to care about the
storage method within `GeometryCollection`. I'm not sure how to
implement that, though.
> Remove manual memory management from GeometryCollection, Polygon

- include/geos/geom/GeometryCollection.h
- include/geos/geom/LineString.h
- include/geos/geom/MultiLineString.inl
- include/geos/geom/MultiPoint.h
- include/geos/geom/MultiPolygon.inl
- include/geos/geom/Point.h
- include/geos/geom/Polygon.h
- src/geom/LinearRing.cpp
- src/geom/MultiLineString.cpp
- src/geom/MultiPoint.cpp
- src/geom/MultiPolygon.cpp
Virtual inheritance is not required, increases the size of all Geometry
subclasses by 8 bytes, and introduces a step of indirection when
accessing Geometry members.
> Remove virtual inheritance in Geometry subclasses

- src/noding/MCIndexNoder.cpp
- src/noding/snapround/MCIndexSnapRounder.cpp
- src/operation/overlay/OverlayOp.cpp
- src/operation/overlay/validate/OffsetPointGenerator.cpp
It is deprecated in C+11 and removed in C++17.
> Remove use of std::mem_fun

- include/geos/geom/CoordinateArraySequence.h
- include/geos/triangulate/quadedge/QuadEdge.h
- include/geos/triangulate/quadedge/QuadEdgeSubdivision.h
- src/geom/CoordinateArraySequence.cpp
- src/triangulate/VoronoiDiagramBuilder.cpp
- src/triangulate/quadedge/QuadEdge.cpp
- src/triangulate/quadedge/QuadEdgeSubdivision.cpp
Net benefit is approximately 20% for Delaunay, 2-3% for Voronoi.
- Avoid copying all triangles after construction
- Avoid inFrame checks if result will be ignored
- Avoid heap-allocating std::vector
- Avoid conversions from unique_ptr to raw pointers
> Delaunay performance enhancements

- benchmarks/ClassSizes.cpp
- benchmarks/capi/GEOSPreparedContainsPerfTest.cpp
- capi/geos_c.cpp
- capi/geos_c.h.in
- capi/geos_ts_c.cpp
- include/geos/geom/CoordinateArraySequence.h
- include/geos/geom/CoordinateSequence.h
- include/geos/geom/FixedSizeCoordinateSequence.h
- include/geos/geom/Makefile.am
- include/geos/geom/Point.h
- src/geom/CoordinateArraySequence.cpp
- src/geom/CoordinateSequence.cpp
- src/geom/GeometryFactory.cpp
- src/geom/Point.cpp
- tests/unit/Makefile.am
- tests/unit/geom/FixedSizeCoordinateSequenceTest.cpp
The latest release of GEOS (3.7) uses four heap allocations to construct a Point geometry through the C API. Excessive heap allocations have been [identified](https://github.com/PDAL/PDAL/issues/1735) as a weakness of GEOS by @hobu and others.
One of the four allocations was trivially avoided and was removed in aff7bcf25a4879d95243c5a60240a4ee0b4a06a6. This PR removes two of the remaining three.
The three heap allocations are as follows:
1) A `GeometryFactory` allocates all returned Geometries on the heap. This is unavoidable if we need to return the Geometry to a C API caller via an opaque pointer, and is not impacted by this PR. Workarounds are possible, such as providing XY variants of C API functions that avoid the need for the caller to manage a point, e.g. …
> Add FixedSizeCoordinateSequence for Points

- doc/CMakeLists.txt
- doc/check_doxygen_errors.cmake
This PR adds doxygen error check for CMake builds with a new target (make doxygen-checked), similar to what’s implemented for autotools.
Implemented with only CMake code it’s supposed to work on any platform, but should be tested.
This is a mirror of https://git.osgeo.org/gitea/geos/geos/pulls/95. Opened the PR here too for testing purposes.
> WIP: Add CMake doxygen error check #988

- src/index/chain/MonotoneChainBuilder.cpp
In most configurations this access would be optimized out (as it is
never used) but this is not always the case.
Fixes #1002
> Avoid access past end of vector

- include/geos/geom/FixedSizeCoordinateSequence.h
- include/geos/geom/Point.h
- src/geom/Point.cpp
- tests/unit/geom/FixedSizeCoordinateSequenceTest.cpp
- tests/unit/geom/PointTest.cpp
Fixes https://trac.osgeo.org/geos/ticket/1001 without reintroducing a heap allocation as #243 does.
> Avoid returning size-1 CoordinateSequence from empty point

- .azure-pipelines.yml
- capi/geos_ts_c.cpp
This PR defines some templates that execute a chunk of code (expressed as a lambda), capture any exceptions, and pass them to the context's error handler.
This allows over 3,000 lines of copy-paste to be removed from `geos_ts_c.cpp`, improving readability/maintainability, and ensures a consistent return value for any error occurring within a function.
There is a very small increase in library file size; on my system, `libgeos_c.a` goes from 390K to 402K. Inspecting the libraries with `nm -C` shows that two of the lambdas (`GEOSWKBWriter_writeHEX_R` and `GEOSWKBWriter_write_r`) are not inlined.
> Remove copy-paste error handling in C API

- .travis.yml
- capi/geos_ts_c.cpp
- include/geos/algorithm/ttmath/ttmathbig.h
- include/geos/operation/distance/DistanceOp.h
- src/algorithm/LineIntersector.cpp
- src/algorithm/MinimumBoundingCircle.cpp
- src/algorithm/Orientation.cpp
- src/geom/LineSegment.cpp
- src/geom/util/CoordinateOperation.cpp
- src/geom/util/ShortCircuitedGeometryVisitor.cpp
- src/io/WKTReader.cpp
- src/operation/distance/DistanceOp.cpp
- src/operation/union/UnaryUnionOp.cpp
- tests/xmltester/SimpleWKTTester.cpp
- tools/ci/script_autotools_scanbuild.sh
Used: `scan-build make`
If you are interested I can try to address the rest of the issues.
> Some issues found by scan-build

- include/geos/algorithm/locate/IndexedPointInAreaLocator.h
- include/geos/geomgraph/GeometryGraph.h
- include/geos/operation/valid/IndexedNestedShellTester.h
- include/geos/operation/valid/IsValidOp.h
- include/geos/operation/valid/Makefile.am
- src/geomgraph/GeometryGraph.cpp
- src/operation/valid/IndexedNestedRingTester.h
- src/operation/valid/IndexedNestedShellTester.cpp
- src/operation/valid/IsValidOp.cpp
- src/operation/valid/Makefile.am
This PR introduces an `IndexedNestedShellTester` class, modelled after
`IndexedNestedRingTester`, to check shell nesting as part of MultiPolygon
validity checking. Relevant methods are yanked out of `IsValidOp`
then updated to use indexes to locate rings relative to each other 
(STRtree) and to check point containment within a ring
(IndexedPointOnAreaLocator).
You need the right geometry for this to matter.
This commit **reduces GEOSisValid runtime for a test geometry (GADM
boundary of Australia) from about 85 seconds to less than 1 second**. It
does not appreciably change runtime for TIGER counties, HydroBASINS
Level 5, or a sample parcel dataset.
> Use spatial index to check shell nesting in IsValidOp

- CMakeLists.txt
- include/CMakeLists.txt
Currently, if `DISABLE_GEOS_INLINE` is `OFF` (the default value) then the `.inl` files are not installed along which causes an issue for consumers down the line.
This PR fixes that behaviour by installing the `.inl` files if required.
> Install inl files if DISABLE_GEOS_INLINE is OFF

- doc/Doxyfile.in
- include/geos/geom/prep/PreparedGeometry.h
- include/geos/geom/prep/PreparedGeometryFactory.h
- include/geos/geom/prep/PreparedPolygonContainsProperly.h
- include/geos/geom/prep/PreparedPolygonCovers.h
- include/geos/geom/prep/PreparedPolygonIntersects.h
- include/geos/geom/prep/PreparedPolygonPredicate.h
- include/geos/operation/distance/IndexedFacetDistance.h
This PR addresses two independent issues with doxygen documentations:
- adds documentation to `IndexedFacetDistance`
- removes the doxygen tags `PERL_PATH` and `MSCGEN_PATH` from Doxyfile.in. The tags are with Doxygen 1.8.16 obsolete, and have not been used in GEOS docs anyway. They will most probably not be missed with earlier versions either.
I'm not sure though, whether the IndexedFacetDistance class description statement that the class is thread-safe also is true for GEOS.
Update:
Additionally, I corrected some bad comment indentation and added some missing brief tags.
> Docs update

- src/algorithm/LineIntersector.cpp
- src/geomgraph/index/SegmentIntersector.cpp
- Fixes a compile-time error when `GEOS_DEBUG` is defined.
- Fixes redefining `DEBUG_INTERSECT` with 0 regardless of its value.
> Minor debug code fixes

- include/geos/noding/IntersectionAdder.h
- include/geos/noding/IteratedNoder.h
- src/noding/IntersectionAdder.cpp
- src/noding/IteratedNoder.cpp
- tests/unit/capi/GEOSNodeTest.cpp
This PR modifies `IteratedNoder` to provide an intersection coordinate for a failed noding, e.g.
`TopologyException: Iterated noding failed to converge after 6 iterations (near -8.064e+06 4.99333e+06)`
It also resolves a memory leak for the error case.
cc @mappingvermont
> Provide location for GEOSNode failure

- capi/geos_ts_c.cpp
- tests/unit/capi/GEOSCAPIDefinesTest.cpp
Previously version included git commit hash at the end.
Git commit hash was [removed](https://github.com/libgeos/geos/commit/7699310f0bc7b3f2a6f300e72164d3fab3e76646#diff-8dd96440c9832c59176dcaa7c346b982R3549), but whitespace was left over.
It breaks ruby ffi-geos library that tries to parse capi version using regex :).
> remove whitespace at the end of capi version

- src/geom/MultiLineString.cpp
- tests/unit/capi/GEOSReverseTest.cpp
- tests/unit/linearref/LengthIndexedLineTest.cpp
Updated for consistency with the behavior of other geometry types (as changed in https://github.com/locationtech/jts/pull/513)
I am inclined to backport this to 3.7.x (where `GEOSReverse` was introduced) since I doubt there are many users of this function and it's difficult to recommend new users (https://github.com/r-spatial/sf/issues/1246) if behavior among GEOS versions is not consistent.
> Retain component order in MultiLineString::reverse

- src/algorithm/CGAlgorithmsDD.cpp
- src/algorithm/Intersection.cpp
- std::isnan() is useless when !std::isfinite() is tested
- std::isnan() || std::isinf() can be replaced by !std::isfinite()
> Use !std::isfinite() to exclude nan and infinite values

- capi/geos_c.cpp
- capi/geos_c.h.in
CLang 9 -Wextra warns about
```
./geos_c.h:1226:9: warning: struct 'WKTReader' was previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Wmismatched-tags]
typedef struct GEOSWKTReader_t GEOSWKTReader;
^
../../include/geos/io/WKTReader.h:58:16: note: previous use is here
class GEOS_DLL WKTReader {
^
./geos_c.h:1226:9: note: did you mean class here?
typedef struct GEOSWKTReader_t GEOSWKTReader;
^~~~~~
class
```
Similarly for WKTWriter, WKBReader and WKBWriter
This is due to capi/geos_c.cpp having a
```
#define GEOSWKTReader_t geos::io::WKTReader
```
Adopt the same solution as for GEOSGeom and other C++ classes
exposed in C API
(Alternative to https://github.com/libgeos/geos/pull/276)
> Fix -Wmismatched-tags warning related to WK[T/B][Reader/Writer]

- include/geos/noding/NodingIntersectionFinder.h
- src/noding/MCIndexSegmentSetMutualIntersector.cpp
- src/operation/union/CascadedPolygonUnion.cpp
- Unused private member --> removed
- Unused method (likely a debugging one) -> protected by #if GEOS_DEBUG
- Unused variables in a destructor -> removed
> Fix a few CLang 9 -Wextra warnings

- include/geos/util.h
- src/geomgraph/DirectedEdgeStar.cpp
- src/geomgraph/EdgeRing.cpp
- src/geomgraph/Node.cpp
- src/geomgraph/PlanarGraph.cpp
- src/noding/IntersectionAdder.cpp
- src/noding/IntersectionFinderAdder.cpp
- src/noding/snapround/SimpleSnapRounder.cpp
- src/operation/buffer/BufferSubgraph.cpp
- src/operation/buffer/OffsetCurveSetBuilder.cpp
- src/operation/buffer/RightmostEdgeFinder.cpp
- src/operation/linemerge/EdgeString.cpp
- src/operation/linemerge/LineMerger.cpp
- src/operation/linemerge/LineSequencer.cpp
- src/operation/overlay/LineBuilder.cpp
- src/operation/overlay/MaximalEdgeRing.cpp
- src/operation/overlay/OverlayOp.cpp
- src/operation/overlay/PolygonBuilder.cpp
- src/operation/polygonize/PolygonizeGraph.cpp
- src/operation/relate/RelateComputer.cpp
- src/operation/relate/RelateNode.cpp
- src/operation/valid/ConnectedInteriorTester.cpp
- src/operation/valid/ConsistentAreaTester.cpp
(Ported from what has been used since a few years in GDAL, which was
added per https://trac.osgeo.org/gdal/ticket/6720)
This function can be used to replace most patterns where a static_cast
or dynamic_cast is done, and we are sure that the result is of the target
type (except programming bugs)
In particular, the following common pattern
```
assert(dynamic_cast<Target*>(foo));
Target* t = static_cast<Target*>(foo);
```
can now been replaced equivalently by
```
Target* t = detail::down_cast<Target*>(foo);
```
The assertion is only done in GEOS_DEBUG mode by down_cast.
This is even safer as it avoids the risk of potentially side effect,
in the assert() as was found in RelateComputer.cpp that had
```
assert(dynamic_cast<RelateNode*>(nodes.addNode(ei.coord)));
RelateNode* n = …
```
> Add a geos::detail::down_cast<To>(From*) function

- .travis.yml
- tools/ci/script_autotools_scanbuild.sh
Recover the Travis scan-build job. With the update to clang-9 and the fixes applied previously, the build is clean (`scan-build: No bugs found.`).
I've set it up as `allow_failures` as requested when it was disabled. I'm not 100% sure if it should be simply enabled (no failures allowed) or not, on one hand it would detect bugs before they are introduced, but on the other hand code/commits that break the build might go into the project without using this CI (thus breaking subsequent PRs). In any case, either if failing is allowed I think it is a good thing to have in the CI as it isn't something usually checked during development.
> Recover scan-build Travis build

- include/geos/geomgraph/PlanarGraph.h
- include/geos/index/bintree/Bintree.h
- include/geos/index/bintree/NodeBase.h
- include/geos/index/strtree/AbstractSTRtree.h
- include/geos/operation/buffer/OffsetSegmentString.h
- include/geos/operation/overlay/EdgeSetNoder.h
- include/geos/operation/overlay/PointBuilder.h
- include/geos/operation/relate/RelateNodeGraph.h
- include/geos/operation/valid/SweeplineNestedRingTester.h
- include/geos/planargraph/Node.h
- include/geos/precision/CommonBitsRemover.h
cppcheck spots classes that have pointer member variables, but lack an
explicit copy constructor and assignment operator. The default behaviour
of bitwise copy is dangerous, so add explicit '= delete'
> include/: add deleted copy constructors and assignment operators

- include/geos/geom/Envelope.h
- include/geos/geom/Envelope.inl
- src/operation/overlay/snap/LineStringSnapper.cpp
- tests/unit/geom/EnvelopeTest.cpp
This PR adds an envelope distance check to `LineStringSnapper`. In my test it improves union performance by 35% for a set of polygons that requires snapping.
This code may end up being replaced with the new overlay engine, but there may be other applications for the `Envelope::distanceToCoordinate` method added here.
> Add envelope short circuit to snapping overlay op

- include/geos/geom/Envelope.h
- include/geos/geom/Envelope.inl
- src/geom/Envelope.cpp
- src/geom/Geometry.cpp
- src/index/strtree/BoundablePair.cpp
- src/operation/distance/DistanceOp.cpp
- tests/unit/geom/EnvelopeTest.cpp
Reduces `GEOSDistance` runtime by 70% on a test set of polygons.
> Add envelope check to DistanceOp::computeMinDistance

- include/geos/math/DD.h
Minimal PR to silence clang (clang version 10.0.1):
```
In file included from DD.cpp:18:
../../include/geos/math/DD.h:122:9: error: definition of implicit copy assignment operator for 'DD' is deprecated because it has a user-declared copy constructor [-Werror,-Wdeprecated-copy]
DD(const DD &dd) : hi(dd.hi), lo(dd.lo) {};
^
DD.cpp:389:15: note: in implicit copy assignment operator for 'geos::math::DD' first required here
r = r*r;
```
> DD: Address clang warning

- include/geos/operation/overlayng/IntersectionPointBuilder.h
- include/geos/operation/overlayng/LineBuilder.h
- include/geos/operation/overlayng/OverlayGraph.h
- include/geos/operation/overlayng/OverlayPoints.h
- include/geos/operation/overlayng/PolygonBuilder.h
- src/operation/overlayng/OverlayGraph.cpp
- tests/xmltester/XMLTester.cpp
So, this is confusing, but here's the explanation:
IF you create a class that you're dllexport'ing, the compiler tries to instantiate all the implicit functions that the class needs at the time that it sees the class. This seems to happen even if you never use those functions or instantiate the class. This is to allow the version in the DLL to be used by the dynamic linker.
Anyway, you can't copy or assign a class with vector<unique_ptr<foo>>, so the compiler complains when it attempts to instantiate the implicit functions that are part of the class.  These changes stop the compiler from trying to create the implicit assign operator and copy ctor.
> Fix windows compilation issues.

- src/io/StringTokenizer.cpp
- src/io/WKTReader.cpp
- tests/unit/io/WKTReaderTest.cpp
* Allow WKT to parse EMPTY within MULTIPOINT elements.
* Fix a bug where getNextToken() would not skip forward empty spaces.
Refs: https://github.com/cockroachdb/cockroach/issues/53997
> io: fix parsing of WKT with EMPTY components

- .azure-pipelines.yml
- src/geomgraph/EdgeIntersectionList.cpp
- src/geomgraph/NodeMap.cpp
- src/geomgraph/PlanarGraph.cpp
- src/geomgraph/index/SegmentIntersector.cpp
- src/index/strtree/AbstractSTRtree.cpp
- src/noding/SegmentNodeList.cpp
- src/operation/IsSimpleOp.cpp
- src/operation/overlayng/MaximalEdgeRing.cpp
- src/operation/relate/EdgeEndBuilder.cpp
- src/operation/relate/EdgeEndBundle.cpp
- src/operation/relate/RelateComputer.cpp
- src/operation/relate/RelateNodeGraph.cpp
- src/simplify/TaggedLineStringSimplifier.cpp
- src/simplify/TopologyPreservingSimplifier.cpp
- tools/cppcheck.sh
And fixes related warnings
Adapted from script used by GDAL, PROJ, QGIS
> Add tools/cppcheck.sh and make it a AZP job

- src/algorithm/Orientation.cpp
- src/io/WKBReader.cpp
- tests/unit/capi/GEOSGeom_setPrecisionTest.cpp
A few unexciting compiler warnings found when building with cmake & gcc 5.5
> Compiler warning fixes

- include/geos/operation/union/OverlapUnion.h
- src/operation/union/CascadedPolygonUnion.cpp
The OverlapUnion optimization actually slows things down, so is being removed.
> Remove OverlapUnion from CascadedPolygonUnion

- .gitignore
- Makefile.am
- NEWS
- configure.ac
- tools/CMakeLists.txt
- tools/geos.pc.cmake
- tools/geos.pc.in
This feature adds support for [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/), which is a helper tool used when compiling applications and libraries on *nix systems. It is similar to `geos-config`, but is more widespread and generic.
Take a look what you might already have, which should already include `proj` and `gdal`:
```
pkg-config --list-all
```
Here is how it works from the command line:
```
export PKG_CONFIG_PATH=/path/to/geos/prefix
pkg-config geos --modversion  # same as `geos-config --version`
pkg-config geos --cflags  # same as `geos-config --cflags`
pkg-config geos --libs  # same as `geos-config --clibs`
```
Or from autotools files for a custom project "myapp":
```
PKG_CHECK_MODULES([GEOS], [geos])
myapp_CFLAGS = $(GEOS_CFLAGS)
myapp_LDADD = $(GEOS_LIBS) …
```
> Feature: add support for pkg-config for GEOS C API (only)

- include/geos/geom/LineSegment.h
- include/geos/geom/LineSegment.inl
- include/geos/geom/PrecisionModel.h
- include/geos/geom/PrecisionModel.inl
- src/geom/PrecisionModel.cpp
The LineSegment and PrecisionModel assignment operators were implicitly
declared because these classes have declared destructors and/or copy
constructors. Since the destructors and copy constructors are not needed,
the warning can be removed by deleting them.
> Clear warnings about deprecated assignment operator 

- capi/geos_ts_c.cpp
- include/geos/geom/FixedSizeCoordinateSequence.h
- src/geom/CoordinateArraySequence.cpp
- tests/unit/capi/GEOSCoordSeqTest.cpp
Closes https://trac.osgeo.org/geos/ticket/1078
And at the same time, also fixed the error message (showing the ordinate index, instead of coordinate index)
> Fix return error code of GEOSCoordSeq_setOrdinate (closes #1078)

- include/geos/geom/Coordinate.h
- include/geos/geom/Coordinate.inl
The previously defined constructor allowed a Coordinate to be constructed
from only a single value, i.e. `Coordinate(3)` would produce `(3, 0, NaN)`.
It's not clear what the use for this is, and it allowed further
complications like `Envelope(3)` compiling by implicitly constructing the
coordinate above.
This commit adds a no-argument constructor to preserve the behavior of
`Coordinate()` producing `(0, 0, NaN)`.
> Remove default arguments for Coordinate constructor

- include/geos/noding/Makefile.am
- include/geos/noding/NodedSegmentString.h
- include/geos/noding/SegmentNode.h
- include/geos/noding/SegmentNode.inl
- include/geos/noding/SegmentNodeList.h
- include/geos/noding/snapround/SnapRoundingNoder.h
- src/noding/NodedSegmentString.cpp
- src/noding/SegmentNode.cpp
- src/noding/SegmentNodeList.cpp
- src/noding/snapround/SnapRoundingNoder.cpp
SegmentNodeList went to great pains to create SegmentNodes with stable
addresses so that pointers to the created SegmentNodes could be passed
to callers. However, the returned pointers were never used. This commit
simplifies SegmentNodeList by storing SegmentNodes directly in nodeMap.
Improves overlay performance by maybe 5%.
> Store SegmentNode values directly in SegmentNodeList

- CMakeLists.txt
This is intended to cover the case where a packager builds with an
undefined build type in order to have all compiler flags drawn from the
environment.
From discussion at https://lists.osgeo.org/pipermail/geos-devel/2021-January/010083.html
cc @sebastic
> [CMake] Make sure that assert() is disabled for any non-Debug build.

- CMakeLists.txt
- tools/CMakeLists.txt
This PR is intended to satisfy a request from @sebastic that we
> Make the CMake build adhere to CMAKE_INSTALL_LIBDIR so that multiarch
keeps working, see this recent example:
> https://github.com/openstreetmap/OSM-binary/issues/54
> A quick look at the CMakeLists.txt for GEOS shows it using hardcoded
paths in its install() calls as well.
> CMake: Use GNUInstallDirs to set install directories

- benchmarks/ClassSizes.cpp
- include/geos/constants.h
- include/geos/io/ByteOrderDataInStream.h
- include/geos/io/ByteOrderDataInStream.inl
- include/geos/io/ByteOrderValues.h
- include/geos/io/WKBReader.h
- include/geos/precision/CommonBits.h
- src/io/ByteOrderValues.cpp
- src/io/WKBReader.cpp
- src/precision/CommonBits.cpp
- tests/unit/io/ByteOrderValuesTest.cpp
- tests/unit/precision/CommonBitsTest.cpp
OGC WKB spec specifies that the integers are unsigned. Use of signed
integers is probably a carryover from Java, which does not have unsigned
integers. Clear type conversion warnings in WKBReader and use C++11
int64_t type.
> Read unsigned integers in WKBReader

- tests/unit/capi/GEOSDensifyTest.cpp
- tests/xmltester/XMLTester.cpp
- tests/xmltester/tests/general/TestDensify.xml
This updates the Densify tests based on what I understood to be the direction in #391.
This uses a function in the C API tests to reduce the boilerplate, and since it is a function in the same file, my understanding was that it wouldn't contribute to a decrease in clarity / usability of the tests.  (Note: the last test checks nulls and needed to be a special case).
This also expands the XML tests used for `Densifier`.  I did a bit of cleanup there to make them easier to add and read:
1) used XML formatter; this makes them a bit longer, but removes all the mental overhead of formatting / alignment.
2) pulled all geometry WKT to left margin so that you can more easily see and compare inputs and outputs; this is arguably one of the most important things to see in these test files.
> TST: Expand XML densify tests, reduce boilerplate in C API densify tests

- include/geos/geom/Envelope.h
- include/geos/geom/Envelope.inl
- include/geos/geom/GeometryCollection.h
- include/geos/geom/LineString.h
- include/geos/geom/Polygon.h
- include/geos/io/WKTReader.h
- src/geom/GeometryCollection.cpp
- src/geom/LineString.cpp
- src/geom/Polygon.cpp
- tests/unit/geom/GeometryCollectionTest.cpp
- tests/unit/geom/LineStringTest.cpp
- tests/unit/geom/PolygonTest.cpp
- tests/unit/io/WKTReaderTest.cpp
This can allow for more efficient implementation implementation of some
operations such as GeometryCombiner. Objects that release their
components are left in an undefined state. This approach is taken
because it is analogous to the state of moved-from objects, and because
reverting the objects to a defined state can be expensive. For example,
an empty Polygon must own an empty LinearRing, which must own an empty
CoordinateSequence.
> Add methods to release objects owned by some Geometry types 

- include/geos/geom/GeometryFactory.h
- include/geos/geom/util/GeometryCombiner.h
- src/geom/util/GeometryCombiner.cpp
- src/operation/union/OverlapUnion.cpp
- tests/unit/geom/util/GeometryCombinerTest.cpp
- tests/unit/utility.h
Add test cases and make "skipEmpty" flag settable. Potentially can be used to avoid copies in cascaded union, but that's a frightening place to go.
> Enable GeometryCombiner to consume its inputs

- include/geos/geom/Envelope.h
- include/geos/geom/Envelope.inl
- include/geos/operation/overlayng/RingClipper.h
- include/geos/triangulate/quadedge/Vertex.h
- src/geom/Envelope.cpp
- src/operation/overlay/OverlayOp.cpp
- src/operation/overlayng/OverlayNGRobust.cpp
- src/operation/overlayng/RingClipper.cpp
- src/triangulate/DelaunayTriangulationBuilder.cpp
- src/triangulate/VoronoiDiagramBuilder.cpp
- src/triangulate/quadedge/QuadEdgeSubdivision.cpp
- tests/unit/capi/GEOSDelaunayTriangulationTest.cpp
- tests/unit/geom/EnvelopeTest.cpp
This allows explicit isNull() checks to be avoided in some of the
envelope operations, since NaN semantics make the affected comparisons
false for null envelopes.
Improves performance of watershed union operation by 1%.
> Represent empty envelope with NaN

- CMakeLists.txt
- appveyor.yml
- src/deps/CMakeLists.txt
- tests/xmltester/CMakeLists.txt
- tests/xmltester/XMLTester.h
This PR is an attempt to stop the propagation of GEOS diagnostic flags to vendored libraries (tinyxml, ryu). The vendored code is moved into `OBJECT` libraries that are treated as separate entities in CMake but end up rolled into the consuming targets (`ryu` sources end up in `libgeos`; there is no `libryu` emitted.)
> Exclude vendored libs from GEOS compiler warnings

- .github/workflows/ci.yml
Follow-up from #417, to ensure things installed via `pip install --user` are available on the PATH.
Also change CMake version `3.12.*` to `3.13.*`, because there was only one release in the 3.12 series.
> CI: add .local/bin to GITHUB_PATH

- include/geos/noding/SegmentNodeList.h
- src/noding/SegmentNodeList.cpp
createSplitPts is usually returning a vector of length 2, so switch to a FixedCoordinateSequence instead.
> Reduce heap allocs in SegmentNodeList

- src/geom/prep/BasicPreparedGeometry.cpp
- tests/unit/capi/GEOSPreparedGeometryTest.cpp
Fixes use case spotted by https://github.com/OSGeo/gdal/issues/3542#issuecomment-792659437
> Fix crash with GEOSPreparedIntersects/Covers on a POINT EMPTY

- NEWS
- benchmarks/CMakeLists.txt
- benchmarks/algorithm/CMakeLists.txt
- benchmarks/algorithm/locate/CMakeLists.txt
- benchmarks/capi/CMakeLists.txt
- benchmarks/capi/GEOSCoordSeqPerfTest.cpp
- benchmarks/geom/CMakeLists.txt
- benchmarks/index/CMakeLists.txt
- benchmarks/index/chain/CMakeLists.txt
- capi/geos_c.cpp
- capi/geos_c.h.in
- capi/geos_ts_c.cpp
- tests/unit/capi/GEOSCoordSeqTest.cpp
Add a method to copy coordinates into a GEOS structure from a contiguous chunk of memory. While this is not as good as using that chunk of memory directly, it greatly simplifies and improves the performance of bringing coordinates into GEOS.
Results of included benchmark show the performance on coordinate sequences of size 10, 1000, and 10 000 relative to existing methods (createByOrdinate: setX/setY and createByCoordinate: setXY)
```
-----------------------------------------------------------------------------------
Benchmark                                         Time             CPU   Iterations
-----------------------------------------------------------------------------------
BM_CoordSeq_CreateByOrdinate<10, 2>             167 ns          167 ns      4181695 …
```
> Add GEOSCoordSeq_copyFromBuffer

- capi/geos_c.cpp
- capi/geos_c.h.in
- capi/geos_ts_c.cpp
- tests/unit/capi/GEOSCoordSeqTest.cpp
Results in cleaner usage for PostGIS (https://github.com/dbaston/postgis/commit/1c4aead9c5b8c166d243f5397b7237cc3087ebc7), avoids future ambiguity about what `dims == 3` means.
> Handle buffers with M in GEOSCoordSeq_copyFromBuffer, GEOSCoordSeq_copyToBuffer

- include/geos/algorithm/distance/DiscreteFrechetDistance.h
- include/geos/algorithm/distance/DiscreteHausdorffDistance.h
- src/algorithm/distance/DiscreteFrechetDistance.cpp
- src/algorithm/distance/DiscreteHausdorffDistance.cpp
- src/geom/util/Densifier.cpp
- tests/unit/algorithm/distance/DiscreteFrechetDistanceTest.cpp
- tests/unit/algorithm/distance/DiscreteHausdorffDistanceTest.cpp
- tests/xmltester/XMLTester.cpp
- tests/xmltester/tests/general/TestDensify.xml
Those pieces of code do things like (integer_type)potential_big_double_value,
which is undefined behavior if the potential_big_double_value is beyond
the validity range of integer_type. Catch that before the cast.
> Avoid undefined behavior in casts in Densify(), DiscreteHausdorffDistance and DiscreteFrechetDistance

- src/noding/SegmentNodeList.cpp
getSplitCoordinates() calls addEdgeCoordinates() repeatdly, which itself
calls std::unique() on the whole coordList, thus iterating from the
start each time, which is a quadratic performance pattern. As
addEdgeCoordinates() is a private method only called by
getSplitCoordinates(), move the call to std::unique() to the end of
getSplitCoordinates() itself.
Issue was detected when observing long runtimes on safe-TestBufferJagged.xml
Before this PR:
$ /home/even/geos/build_cmake/bin/test_xmltester -v /home/even/geos/tests/xmltester/tests/misc/safe-TestBufferJagged.xml
/home/even/geos/tests/xmltester/tests/misc/safe-TestBufferJagged.xml: case1: test1: buffer(a, 0.35): ok. (11 ms)
/home/even/geos/tests/xmltester/tests/misc/safe-TestBufferJagged.xml: case1: test2: buffer(a, 0.75): ok. (155 ms) …
> SegmentNodeList::getSplitCoordinates(): fix quadratic performance pattern

- src/geom/HeuristicOverlay.cpp
Fixes [#1116](https://trac.osgeo.org/geos/ticket/1116); `#ifdef` statements were used on a macro that was already defined; correct to use `#if` like the rest of the file.
> Fix Accidentally Enabled HeuristicOveraly Debugging

- include/geos/geom/LineSegment.h
- src/geom/LineSegment.cpp
Those methods already compute the projection factor, but then call
project() which recomputes it again. Avoid that duplicated computation.
Didn't identify this as a hotspot, but should save a few CPU cycles.
> LineSegment: tiny improvement in project(const LineSegment&, ...) and  closestPoint()

- include/geos/operation/buffer/BufferOp.h
When instance variable resultGeometry is computed by a call to
getResultGeometry() it is never freed by the BufferOf instance.
It is the responisibilty of the caller to free this object.
This change documents the ownership transfer intent.
> Bufferop::getResultGeometry() documentation

- tools/CMakeLists.txt
Closes [gh-460](#460) (should there be a Trac ticket?)
There was a bit of discussion in 7e8575f4c8672fb51d28601f82ec724477220084 regarding the CMake name format for these options.
> CMake: add option BUILD_ASTYLE, with default ON

- src/io/WKBReader.cpp
numRings is unsigned, and we have tested just above if it was 0 and
returned if it was. Consequently at that point, it is > 0
Spotted by cppcheck
> Remove always true check

- src/index/kdtree/KdTree.cpp
Fixes https://github.com/qgis/QGIS/issues/45226
While we are it, also avoid recursive formulation for queryNodePoint()
Could be worth backporting to 3.9 branch
> KdTree::queryNode(): rewrite it to avoid blowing up the stack

- src/io/GeoJSONReader.cpp
- tests/unit/io/GeoJSONReaderTest.cpp
json::operator[] is advertised as having undefined behavior when the
request member doesn't exist or the json item is not an object.
json::at() is similar but emits a C++ exception on those situations.
Fixes #1138
> GeoJSON reader: fix crashes (in debug mode) on invalid GeoJSON

- include/geos/noding/snapround/SnapRoundingIntersectionAdder.h
- include/geos/noding/snapround/SnapRoundingNoder.h
- src/noding/snapround/SnapRoundingIntersectionAdder.cpp
- src/noding/snapround/SnapRoundingNoder.cpp
- tests/unit/capi/GEOSGeom_setPrecisionTest.cpp
Fix for "GEOSGeom_setPrecision returns error for valid geometry" https://trac.osgeo.org/geos/ticket/1127
`nearnessTol` calculation moved from SnapRoundingIntersectionAdder to SnapRoundingNoder; same tolerance value is passed to MCIndexNoder.  This allows to detect all cases of vertices positioned close enough to segments to be added as intersections by SnapRoundingIntersectionAdder::processNearVertex.  Currently closely positioned segments can be filtered out in `MonotoneChain::computeOverlaps()` by `MonotoneChain::overlaps()` called with zero `overlapTolerance`.
> SnapRoundingNoder fix

- include/geos/index/strtree/TemplateSTRtree.h
Tentative fix for #490
It avoids using the `end()` iterator which, under a very strict interpretation of the C++ specifications, should be invalid after an `emplace_back`
> do not use end() iterators

- NEWS.md
Converts the NEWS file to a markdown file, NEWS.md. This enables markdown layout, including headings, URLs and references to issues and pull requests.
> DOCS: Convert NEWS to NEWS.md enabling Markdown layout

- .github/workflows/ci.yml
This will catch runtime exceptions that may not be thrown in a Release build.
> Test Debug build with MSVC22

- web/content/usage/download.md
The documentation suggests using the tar flag 'z', but it appears that downloads are bzipped instead of gzipped, so 'j' should be the recommended flag.
> docs: update flags used in tar example

- include/geos/algorithm/ConvexHull.h
- include/geos/geomgraph/index/SegmentIntersector.h
- include/geos/operation/overlayng/EdgeKey.h
This commit adds inline.h includes in all remaining files that were including an .inl file conditionally based on `GEOS_INLINE`.
Fixes #524
> inline: ensure inline.h is included in all .inl includers

- src/index/chain/MonotoneChainBuilder.cpp
- tests/unit/geom/Geometry/differenceTest.cpp
- tests/unit/index/chain/MonotoneChainBuilderTest.cpp
See https://github.com/libgeos/geos/issues/539
> Fix MonotoneChainBuilder::getChain with empty CoordinateString

- NEWS
- src/index/chain/MonotoneChainBuilder.cpp
- tests/unit/geom/Geometry/differenceTest.cpp
- tests/unit/index/chain/MonotoneChainBuilderTest.cpp
See https://github.com/libgeos/geos/issues/539
> [3.10] Fix MonotoneChainBuilder::getChain with empty CoordinateString

- .github/workflows/ci.yml
- CMakeLists.txt
- benchmarks/algorithm/CMakeLists.txt
- benchmarks/algorithm/locate/CMakeLists.txt
- benchmarks/capi/CMakeLists.txt
- benchmarks/geom/CMakeLists.txt
- benchmarks/index/CMakeLists.txt
- benchmarks/index/chain/CMakeLists.txt
- capi/CMakeLists.txt
- tests/superbuild.CMakeLists.txt
Currently GEOS doesn't work as a subproject in CMake via `add_subdirectory()` or FetchContent. 
[Example hello-world super-project](https://gist.github.com/rcoup/2bb5a8b6f0f9d7c26d83f285a7dd314a) & current output.
This is a series of fixes that move GEOS from erroring during generation to building & linking as a CMake subproject:
1. stops using `CMAKE_SOURCE_DIR`/`CMAKE_BINARY_DIR` since they're relative to the top-level project which may not be GEOS.
2. expose `GEOS::geos_c` and `GEOS::geos` alias targets, which is what `find_package(GEOS CONFIG)` has already
3. don't setup testing, packaging, developer-mode, etc when GEOS is a subproject. Moves the `project()` call as early as possible to use [`PROJECT_IS_TOP_LEVEL`](https://cmake.org/cmake/help/latest/variable/PROJECT_IS_TOP_LEVEL.html) …
> CMake: improvements so GEOS works as a subproject

- src/operation/buffer/OffsetCurve.cpp
Was casually discovered when analyzing a warning from a recent cppcheck build
which complained about potential nullptr dereference on the final
"return maxPoly->clone()". I've slightly reworked the loop to make it obvious
this can't happen.
> OffsetCurve::getBufferOriented(): return poly.clone() when numGeometries == 1

- benchmarks/capi/GEOSCoordSeqPerfTest.cpp
- capi/geos_ts_c.cpp
- include/geos/geom/CoordinateArraySequence.h
- src/geom/CoordinateArraySequence.cpp
- Switch from std::memcpy to value copy
- Check for `CoordinateArraySequence` (likely) and so we can inline in that case
```
2022-02-06T12:43:43-05:00
Running bin/perf_capi_coordseq
Run on (8 X 3899.07 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x4)
L1 Instruction 32 KiB (x4)
L2 Unified 256 KiB (x4)
L3 Unified 6144 KiB (x1)
Load Average: 1.96, 2.98, 2.84
-----------------------------------------------------------------------------------
Benchmark                                         Time             CPU   Iterations
-----------------------------------------------------------------------------------
BM_CoordSeq_CopyByCoordinate<10, 2>            30.0 ns         30.0 ns     23397094
BM_CoordSeq_CopyToBuffer<10, 2>                18.5 ns         18.5 ns     38914047 …
```
> Minor perf improvement to GEOSCoordSeq_copyToBuffer

- NEWS.md
- benchmarks/capi/CMakeLists.txt
- benchmarks/capi/GEOSGeom_transformXYPerfTest.cpp
- capi/geos_c.cpp
- capi/geos_c.h.in
- capi/geos_ts_c.cpp
- tests/unit/capi/GEOSGeom_transformXYTest.cpp
Resolves #560
Allows caller to provide a callback function to transform x,y values of all cordinates in a geometry and return a new geometry; z values are unchanged.
Many thanks to @dbaston for providing >95% of the implementation in #560; I mostly tweaked a few things and added tests / benchmarks.
I diverged a bit from the direction suggested in #560, specifically:
* I retained the `XY` suffix on the function names (`GEOSGeom_transformXY`, `GEOSTransformXYCallback`); I think this provides a very clear signal to the user that these apply only to x,y coordinates and helps avoid future ambiguity if an XYZ form is ever added.  This follows the precedent for some of the other XY coordinate sequence getters / setters.  As a user of the library, the `XY` suffix has been helpful and appreciated. …
> ENH: add GEOSGeom_transformXY to C API

- src/geomgraph/index/SegmentIntersector.cpp
- tests/unit/operation/relate/RelateOpTest.cpp
A port of the fix for `SegmentIntersector` in [JTS-839](https://github.com/locationtech/jts/pull/839).
Fixes #565
> Fix RelateOp intersects for points near boundary

- util/CMakeLists.txt
This PR allows an installed `geosop` to be run without requiring `LD_LIBRARY_PATH`. E.g. see:
```
$ mkdir build && cd build
$ cmake -DCMAKE_INSTALL_PREFIX=/tmp/geos-main ..
...
$ make
...
$ make install
...
-- Installing: /tmp/geos-main/bin/geosop
-- Set runtime path of "/tmp/geos-master/bin/geosop" to "$ORIGIN/../lib"
...
$ readelf -d /tmp/geos-main/bin/geosop 
Dynamic section at offset 0x52810 contains 31 entries:
Tag        Type                         Name/Value
0x0000000000000001 (NEEDED)             Shared library: [libgeos.so.3.11.0]
0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
0x000000000000001d (RUNPATH) …
```
> Use relative CMAKE_INSTALL_RPATH for geosop

- NEWS.md
- include/geos/operation/valid/IsSimpleOp.h
- src/operation/valid/IsSimpleOp.cpp
- tests/unit/operation/valid/IsSimpleOpTest.cpp
- tests/xmltester/tests/general/TestSimple.xml
Fix `IsSimpleOp` for closed lines with repeated endpoints
Port of [JTS-851](https://github.com/locationtech/jts/pull/851)
To fix [Shapely-1343](https://github.com/shapely/shapely/issues/1343).
> Fix `IsSimpleOp` for closed lines with repeated endpoints

- tests/unit/geos_unit.cpp
Improve the error handling and messages of the unit test runner application `test_geos_unit`:
* report invalid options
* if group name is invalid, report with an appropriate error message
> Improve unit test runner

- include/geos/geom/FixedSizeCoordinateSequence.h
- src/triangulate/quadedge/QuadEdgeSubdivision.cpp
* Avoid potential buffer overrun by copy in FixedSizeCoordinateSequence
* Disable Voronoi Diagram use of userData to avoid returning pointer to stack mem
> Fix memory-handling bugs found by GCC 12

- include/geos/geom/FixedSizeCoordinateSequence.h
Adds a size check and `assert` to `FixedSizeCoordSeq.setPoints`.  
Also prevents copying to zero-length sequence.
> Add assert and size check to FixedSizeCoordSeq.setPoints

- include/geos/util.h
Should `#if GEOS_DEBUG  ... #endif` be removed around `assert(...)`?
> GEOS_DEBUG: missing header fix

- include/geos/geom/FixedSizeCoordinateSequence.h
- src/triangulate/quadedge/QuadEdgeSubdivision.cpp
* Add size check to `FixedSizeCoordinateSequence.setPoints`
* Remove `QuadEdgeSubdivision` setting user data to local storage
> Fix issues found by compiler warnings

- src/operation/linemerge/LineMerger.cpp
- tests/unit/operation/linemerge/LineMergerTest.cpp
A fix for directed line merging.
* In the first step, 2nd degree nodes can be start nodes in directed case, because both directed edges can be incoming or outgoing.
* Test case had wrong input WKT (but consistent with result).
`(1) <- (2) <- (3) -> (4)`
In this case, `(3)` is clearly a start node but has degree 2. If is is skipped in `buildEdgeStringsForNonDegree2Nodes`, then `buildEdgeStringsForUnprocessedNodes` creates a `LineString` starting from `(2) -> (1)`, since this edge is not marked yet.
> Directed line merge fix

- CMakeLists.txt
since the change from autoconf to cmake this header was not longer installed with `make install`
> install geos.h header file in cmake builds

- src/operation/overlayng/OverlayNG.cpp
- tests/unit/operation/overlayng/CoverageUnionNGTest.cpp
Fix OverlayNG `geomunion` to avoid emitting lines in result.  This fixes `CoverageUnion` for some cases.
> Fix OverlayNG geomunion to stop lines in result

- web/content/usage/download.md
You may find that modern browsers (e.g. Chrome) don't always download non-secure HTTP links. Note that the OSGeo Download server does support HTTPS and has a valid certificate, so HTTPS should be promoted instead.
Related: https://trac.osgeo.org/osgeo/ticket/2775
> Use HTTPS for download.osgeo.org links

- include/geos/index/SpatialIndex.h
- include/geos/index/VertexSequencePackedRtree.h
- include/geos/noding/SegmentNodeList.h
- include/geos/operation/buffer/OffsetCurve.h
- include/geos/precision/CommonBitsRemover.h
- include/geos/triangulate/polygon/PolygonEarClipper.h
Remove invalid `@return`docstrings for void methods. Fixes currently failing `test_docs`.
> Fix multiple docstring issues

- tools/geos-config.in
Now that autotools is gone, the library never has the version number appended, but `geos-config` was still referencing the name with the version suffix.
> geos-config: remove reference to geos-3 library

- capi/geos_c.h.in
- tests/unit/capi/GEOSEnvelopeTest.cpp
Added tests for point/empty inputs. I think it would have been preferable to return a degenerate polygon, but probably not worth changing longstanding behavior.
> Fix docs, add tests for GEOSEnvelope edge cases

- NEWS.md
I was wondering in which version the WKB serialization of POINT EMPTY was changed, and didn't find that in the changelog, only in a commit https://github.com/libgeos/geos/commit/466cff135c8e504632ae38b79a1348dbadb390f1. So thought to add it to the NEWS in case someone else would also look for that in the future. 
And also noticed that another CAPI addition was missing for 3.11
> DOC: add missing entry to NEWS (empty points change)

- util/geosop/GeosOp.cpp
geosop crashes when the WKT type is an unknown type.
Catching the exception solves this issue.
before:
```shell
$ ./build/bin/geosop intersection -a "LINESTRINGZ(1 1 -1, 1 1 1)" -b "POLYGON((0 0, 0 2, 2 2, 2 0, 0 0))" -f wkt
ABRT
$ ./build/bin/geosop intersection -a "LINESTRING(1 1 -1, 1 1 1)" -b "POLYGONZ((0 0, 0 2, 2 2, 2 0, 0 0))" -f wkt
ABRT
```
after:
```shell
$ ./build/bin/geosop intersection -a "LINESTRINGZ(1 1 -1, 1 1 1)" -b "POLYGON((0 0, 0 2, 2 2, 2 0, 0 0))" -f wkt
ParseException: Unknown type: 'LINESTRINGZ'
$ ./build/bin/geosop intersection -a "LINESTRING(1 1 -1, 1 1 1)" -b "POLYGONZ((0 0, 0 2, 2 2, 2 0, 0 0))" -f wkt
ParseException: Unknown type: 'POLYGONZ'
```
linestringz/polygonz could/must be accepted, but there is an issue for that.
> geosop: GeosOp.cpp: catch ParseException

- README.md
Replaces #675 as discussed with @dr-jts.
> Replace scripting language bindings with link to all language bindings

- NEWS.md
- benchmarks/capi/GEOSPreparedContainsPerfTest.cpp
- capi/geos_c.cpp
- capi/geos_c.h.in
- capi/geos_ts_c.cpp
- include/geos/geom/Envelope.h
- include/geos/geom/Geometry.h
- include/geos/geom/Point.h
- src/geom/Envelope.cpp
- src/geom/Geometry.cpp
- src/geom/Point.cpp
- tests/unit/capi/GEOSPreparedGeometryTest.cpp
- tests/unit/geom/PointTest.cpp
This PR adds a function `GEOSPreparedXY` to the C API to allow point-in-polygon tests without the overhead of point construction. The significance of this overhead depends on the data. When checking many points against a complex boundary, this PR makes almost no difference:
```
bin/perf_geospreparedcontains ~/data/australia.txt 100000
```
With smaller polygons, it makes a measurable improvement (about 20%)
```
bin/perf_geospreparedcontains ~/data/wsa_individual.wkt 500
```
The C++ code surrounding prepared geometries is relatively complex, so rather than modify it to thread a `Coordinate` object through, I modified the C API `GEOSContextHandle` to hold a mutable `Point` object.
The existing API for modifying a `Point` is rather complex and slow. This is the best I could do:
```
struct …
```
> Add GEOSPreparedContainsXY to C API

- src/geom/prep/PreparedPolygonPredicate.cpp
- src/geom/util/ComponentCoordinateExtracter.cpp
- src/noding/MCIndexSegmentSetMutualIntersector.cpp
- tests/unit/geom/prep/PreparedGeometryTest.cpp
Fixes handling of EMPTY elements in PreparedGeometry methods, by add empty coordinate sequence guards in several places.
See https://github.com/locationtech/jts/pull/904
> Fix PreparedGeometry for EMPTY elements

- include/geos/operation/union/CoverageUnion.h
- include/geos/shape/fractal/HilbertEncoder.h
- src/operation/union/CoverageUnion.cpp
- src/shape/fractal/HilbertEncoder.cpp
This PR makes `CoverageUnion` pre-sort its inputs using `HilbertEncoder`. This improves performance by about 50% on my test data set:
Before:
```
bin/geosop -t -q -a ~/data/tl_2021_counties_unsorted.wkt coverageUnion
Ran 1 coverageUnion ops ( 8,092,118 vertices)  -- 4,654,931 usec    (GEOS 3.12.0dev)
```
After:
```
bin/geosop -t -q -a ~/data/tl_2021_counties_unsorted.wkt coverageUnion
Ran 1 coverageUnion ops ( 8,092,118 vertices)  -- 2,238,353 usec    (GEOS 3.12.0dev)
```
> Improve CoverageUnion performance by pre-sorting inputs

- include/geos/geom/GeometryFactory.h
- include/geos/operation/BoundaryOp.h
- include/geos/operation/relate/RelateComputer.h
- src/geom/GeometryFactory.cpp
- src/geom/LineString.cpp
- src/geom/MultiLineString.cpp
- src/operation/BoundaryOp.cpp
- src/operation/relate/RelateComputer.cpp
- tests/unit/geom/GeometryFactoryTest.cpp
- tests/unit/operation/BoundaryOpTest.cpp
- tests/unit/operation/relate/RelateBoundaryNodeRuleTest.cpp
- tests/xmltester/tests/general/TestRelateLA.xml
- tests/xmltester/tests/general/TestRelateLL.xml
This PR fixes the following Trac ticket: https://trac.osgeo.org/geos/ticket/1096. It ports https://github.com/locationtech/jts/pull/671.
As a side effect, it brings along the `BoundaryOp` class that has been in JTS for some time, and its associated tests.
> Fix RelateOp for empty geometry and closed linear geometry

- src/operation/linemerge/LineMerger.cpp
- tests/unit/operation/linemerge/LineMergerTest.cpp
Fixes https://trac.osgeo.org/geos/ticket/401
> LineMerger: Recursively collect all components from GeometryCollections

- CMakeLists.txt
- include/geos/operation/distance/FacetSequenceTreeBuilder.h
- tests/unit/capi/GEOSGeom_createCollectionTest.cpp
This is on by default for clang but not for gcc. This change makes it easier for developers working with gcc to reproduce CI failures without switching toolchains.
> CMake: Add -Wsign-conversion

- NEWS.md
- include/geos/geom/CoordinateArraySequence.h
- include/geos/geom/CoordinateSequence.h
- include/geos/geom/CoordinateSequenceIterator.h
- include/geos/geom/FixedSizeCoordinateSequence.h
- src/geom/CoordinateArraySequence.cpp
- src/geom/CoordinateSequence.cpp
- tests/unit/geom/CoordinateSequenceIteratorTest.cpp
This adds an iterator to `CoordinateSequence` so that class can be used with STL algortithms
```
std::sort(seq.begin(), seq.end());
```
and range for loops,
```
for (auto& coord : seq_) {
coord.y = 2*coord.x;
}
// Use const iterator to check values
std::size_t i = 0;
for (const auto& coord : seq_) {
ensure_equals(coord.x, static_cast<double>(i));
ensure_equals(coord.y, 2*coord.x);
i++;
}
```
This does not reduce the overhead of virtual Coordinate access; that requires #674 .
> Add CoordinateSequenceIterator

- include/geos/geom/Envelope.h
- include/geos/geom/prep/PreparedLineString.h
- include/geos/geom/prep/PreparedLineStringDistance.h
- include/geos/geom/prep/PreparedPolygon.h
- include/geos/geom/prep/PreparedPolygonDistance.h
- include/geos/index/strtree/TemplateSTRNodePair.h
- include/geos/index/strtree/TemplateSTRtree.h
- include/geos/index/strtree/TemplateSTRtreeDistance.h
- include/geos/operation/distance/IndexedFacetDistance.h
- src/geom/prep/PreparedLineString.cpp
- src/geom/prep/PreparedLineStringDistance.cpp
- src/geom/prep/PreparedPolygon.cpp
- src/geom/prep/PreparedPolygonDistance.cpp
- src/operation/distance/IndexedFacetDistance.cpp
- tests/unit/operation/distance/IndexedFacetDistanceTest.cpp
This seems preferable to delegating to the brute-force method of the underlying geometry.
> Use indexed method for PreparedGeometry::isWithinDistance

- include/geos/operation/cluster/AbstractClusterFinder.h
- include/geos/operation/cluster/Clusters.h
- include/geos/operation/cluster/DBSCANClusterFinder.h
- include/geos/operation/cluster/DisjointOperation.h
- include/geos/operation/cluster/EnvelopeDistanceClusterFinder.h
- include/geos/operation/cluster/EnvelopeIntersectsClusterFinder.h
- include/geos/operation/cluster/GeometryDistanceClusterFinder.h
- include/geos/operation/cluster/GeometryFlattener.h
- include/geos/operation/cluster/GeometryIntersectsClusterFinder.h
- include/geos/operation/cluster/UnionFind.h
- src/operation/cluster/AbstractClusterFinder.cpp
- src/operation/cluster/Clusters.cpp
- src/operation/cluster/DBSCANClusterFinder.cpp
- src/operation/cluster/GeometryFlattener.cpp
- src/operation/cluster/UnionFind.cpp
- tests/unit/operation/cluster/ClusterFinderTest.cpp
- tests/unit/operation/cluster/GeometryFlattenerTest.cpp
- util/geosop/GeomFunction.cpp
- util/geosop/GeosOp.cpp
This PR is a rebase of #388 which died on the vine in 2021. It adds the DBSCAN, simple distance, and intersection clustering methods available in PostGIS. Also adds clustering based on envelope intersection and envelope distance.
> Add clustering functions

- include/geos/noding/SegmentStringUtil.h
- src/algorithm/locate/SimplePointInAreaLocator.cpp
These changes improve performance by about 25% in the following test whose runtime is almost exclusively prepared polygon intersection testing with many large/multipart polygons.
```
geosop clusterIntersecting -t -q -r 10 -a ~/data/world.wkt
```
The performance testing was done on top #688 but these changes are independent of it.
> Optimization to prepared polygon intersection

- NEWS.md
- include/geos/geom/prep/PreparedPolygonDistance.h
- src/geom/prep/PreparedPolygonDistance.cpp
- tests/unit/capi/GEOSPreparedDistanceTest.cpp
- tests/unit/capi/GEOSPreparedDistanceWithinTest.cpp
- util/geosop/GeomFunction.cpp
The implementation of `PreparedPolygonDistance` begins with a call to `PreparedPolygonIntersects` to cover the case where a containment relationship exists between the target and test geometries. However, the segment intersection test performed by `PreparedPolygonIntersects` is unnecessary. If any segment intersect, they will be found by `IndexedFacetDistance`.
This PR improves the performance of `PreparedPolygonDistance` by performing the PIP containment tests directly within `PreparedPolygonDistance` and avoiding the call to `PreparedPolygonIntersects`. In the following performance test, which relies heavily on `PreparedPolygonDistance`, runtime is reduced by 45%.
`bin/geosop clusterWithin 1e-3 -t -q -a ~/data/world.wkt`
This should bring additional performance improvements to #692.
> Optimize prepared polygon distance

- src/geom/LineSegment.cpp
- tests/unit/geom/LineSegmentTest.cpp
Fix `LineSegment.orientationIndex(LineSegment)` to have correct result for the case of a non-collinear segment on the right side of the target segment.
Port of https://github.com/locationtech/jts/pull/914
> Fix LineSegment.orientationIndex(LineSegment)

- include/geos/geom/LineSegment.h
- src/operation/buffer/SubgraphDepthLocater.cpp
Fixes the `DepthSegment` comparator to ensure it meets the standard contract for comparisons.
Fixes #703.
> Fix DepthSegment comparison op

- include/geos/operation/overlayng/OverlayNG.h
- include/geos/operation/overlayng/OverlayPoints.h
- src/algorithm/locate/IndexedPointInAreaLocator.cpp
- src/operation/overlayng/OverlayMixedPoints.cpp
- src/operation/overlayng/OverlayPoints.cpp
- tests/unit/operation/overlayng/OverlayNGGeometryCollectionTest.cpp
- tests/xmltester/tests/general/TestNGOverlayGC.xml
Adds support for simple GeometryCollection inputs to OverlayNG.
A simple GeometryCollection is one which can be flattened to a valid Multi-geometry; i.e. it is homogeneous and has no overlapping Polygon compents.
Port of https://github.com/locationtech/jts/pull/915
> Add OverlayNG support for simple GeometryCollection inputs

- src/simplify/TopologyPreservingSimplifier.cpp
- tests/unit/simplify/TopologyPreservingSimplifierTest.cpp
Fixes `TopologyPreservingSimplifier` to have a deterministic ordering for processing Multi-geometries, thus ensuring simplified results are stable.
Fixes #667
> Fix TopologyPreservingSimplifier to produce stable results for Multi inputs

- src/algorithm/ConvexHull.cpp
- tests/unit/algorithm/ConvexHullTest.cpp
Improves the robustness of the radial sorting used by the `ConvexHull` Graham scan algorithm.
Fixes #722.
Port of https://github.com/locationtech/jts/pull/927
> Improve ConvexHull radial sort robustness

- .github/workflows/ci.yml
- include/geos/geom/FixedSizeCoordinateSequence.h
- include/geos/util.h
- src/io/WKTReader.cpp
- src/noding/SegmentNodeList.cpp
Closes #589. RHEL7 (uses gcc 4.8) is fully EOL in spring of 2024, so we'll be rolling this out only about 9 months before then.
> Remove RETURN_UNIQUE_PTR and support for gcc-4.8

- include/geos/triangulate/quadedge/QuadEdgeSubdivision.h
- src/triangulate/quadedge/QuadEdgeSubdivision.cpp
- tests/unit/triangulate/DelaunayTest.cpp
- tests/unit/triangulate/VoronoiTest.cpp
- tests/unit/triangulate/quadedge/QuadEdgeSubdivisionTest.cpp
Increases the size of the "frame" used to initialize the Incremental Delaunay Triangulation subdivision. This improves the robustness of constructing triangulations which contain very narrow triangles along the edge of the subdivision.
Originally reported as a failure in the Concave Hull algorithm in #719. The failure was caused by the constructed triangulation failing to contain triangles which covered the convex hull of the input.
Fixes #719
> More robust Delaunay Triangulation frame size heuristic

- src/operation/buffer/SubgraphDepthLocater.cpp
- Remove a seemingly incorrect short-circuit that skips a buffer subgraph if it lies to the right of a rightward-extending ray
- Add envelope short-circuits for individual DirectedEdges
Improves runtime of Australia buffer benchmark by 75%.
```
bin/geosop -q -t -a ~/data/australia.txt buffer 1e-3
```
> Improve short-circuits in SubgraphDepthLocater

- CMakeLists.txt
- include/geos/algorithm/locate/IndexedPointInAreaLocator.h
- include/geos/export.h
- include/geos/geom/Location.h
This PR is based on patching in vcpkg. Originally contributed to enable builds with clang-cl, I modified it to cover mingw builds. This change reduced the C++ import lib on mingw by one third.
> Extend msvc (DLL) configuration to clang-cl and mingw

- include/geos/noding/BasicSegmentString.h
- include/geos/noding/NodableSegmentString.h
- include/geos/noding/NodedSegmentString.h
- include/geos/noding/SegmentString.h
- include/geos/operation/overlayng/Edge.h
- src/noding/BasicSegmentString.cpp
- src/noding/NodedSegmentString.cpp
- src/operation/overlayng/Edge.cpp
- tests/unit/operation/overlayng/OverlayGraphTest.cpp
Since all SegmentStrings are backed by a CoordinateSequence, we can pull the CoordinateSequence into the base class so that SegmentString::getCoordinate will no longer be virtual and can be inlined. When tested on top of #721 it provides about a 2% performance gain, but it can be applied independently.
> Pull CoordinateSequence into SegmentString base class

- include/geos/geomgraph/Depth.h
- include/geos/geomgraph/TopologyLocation.h
- include/geos/io/WKTWriter.h
- include/geos/operation/overlayng/OverlayLabel.h
- include/geos/shape/fractal/HilbertCode.h
- include/geos/shape/fractal/MortonCode.h
Without the change build on `gcc-13` fails as:
geos/include/geos/geomgraph/TopologyLocation.h:143:52: error: 'uint32_t' has not been declared
143 |     bool isEqualOnSide(const TopologyLocation& le, uint32_t locIndex) const
|                                                    ^~~~~~~~
> geos: add missing <cstdint> includes for gcc-13

- capi/geos_c.h.in
- include/geos/geom/CoordinateSequence.h
I wanted to do a small update to just fix the comment for `GEOSCoordSeq_create` after https://github.com/libgeos/geos/pull/753 fixed that you can pass `dims=4` as well. 
However, then noticed some other places that are no longer up to date as well, but it's a bit a question how far to go with updating all notes about supporting M values (since the support is quite limited)?
> DOC: update GEOSCoordSeq_create doc comment about dimension argument

- NEWS.md
- include/geos/geom/Geometry.h
- include/geos/geom/GeometryCollection.h
- include/geos/geom/MultiLineString.h
- include/geos/geom/MultiPoint.h
- include/geos/geom/MultiPolygon.h
- src/geom/GeometryCollection.cpp
- src/geom/prep/PreparedLineStringIntersects.cpp
- tests/unit/geom/GeometryCollectionTest.cpp
- tests/unit/geom/LineStringTest.cpp
- tests/unit/geom/MultiLineStringTest.cpp
- tests/unit/geom/MultiPointTest.cpp
- tests/unit/geom/MultiPolygonTest.cpp
- tests/unit/geom/PointTest.cpp
- tests/unit/geom/PolygonTest.cpp
- tests/xmltester/tests/general/TestPreparedPredicatesWithGeometryCollection.xml
@dr-jts JTS appears to be affected by the same issue.
> PreparedLineStringIntersects: Fix incorrect result for mixed-dim GC with points

- NEWS.md
- include/geos/index/strtree/Interval.h
- src/geom/Geometry.cpp
- tests/unit/capi/GEOSIntersectsTest.cpp
This PR changes `Geometry::intersects` and `Geometry::disjoint` to use `PreparedGeometry` instead of `RelateOp`. Relative to the `RelateOp` implementation, the prepared intersection is more robust (e.g., https://github.com/libgeos/geos/issues/766) and is faster for both complex and simple polygons, even if the object is only used a single time.
A quick benchmark shows the performance difference in cases of relatively complex polygons (left) and triangles (right), using the GEOS `perf_intersection`, which combines index querying, intersects testing, and intersection overlay.
> Delegate Geometry::intersects to PreparedGeometry::intersects

- src/operation/valid/RepeatedPointRemover.cpp
`LinearRing` was somewhat recently changed to allow construction from a `CoordinateSequence` with length 3. I don't think the `RepeatedPointRemover` was intended to be inconsistent with this.
> RepeatedPointRemover: Allow creating LinearRing of length 3

- include/geos/geom/prep/PreparedPolygon.h
- src/geom/prep/PreparedPolygon.cpp
This provides better performance in cases where the prepared polygon is only used for one test.
I think it would be possible to take this a bit further and tell the `PreparedPolygonFactory` how many times the prepared geometry is expected to be queried. This hint could then be used for some more sophisticated algorithm selection. But this is a good improvement for now.
With this PR, the single-use prepared geometry used by `Geometry::intersects` outperforms `RelateOp` for all scenarios in the JTS benchmark.
> PreparedPolygonIntersects: Use SimplePointInAreaLocator for first test

- src/noding/NodingIntersectionFinder.cpp
The test for adjacent segments may give an incorrect result due to unsigned integer wraparound when segIndex0 > segIndex1. This apparently did not occur until d210a94fe.
Fixes https://github.com/libgeos/geos/issues/770
> NodingIntersectionFinder: Fix false-positive intersection

- .github/workflows/ci.yml
This PR adds a 32-bit build to GitHub Actions. We previously had a 32-bit build using gcc 4.8 but this was recently removed from the matrix.
> CI: Add 32-bit build

- capi/geos_ts_c.cpp
On `Apple clang version 14.0.0 (clang-1400.0.29.202)` compiling `geos_ts_c.cpp` with `-Werror,-Wdeprecated-declarations` fails with:
>  'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.
This is the only use of `sprintf` I could find and since the buffer is already constant sized it makes sense to use `snprintf` instead to remove the warning.
> Remove warning by changing sprintf to snprintf in geos_ts_c.cpp 

- NEWS.md
- benchmarks/algorithm/VoronoiPerfTest.cpp
- capi/geos_c.cpp
- capi/geos_c.h.in
- capi/geos_ts_c.cpp
- include/geos/triangulate/VoronoiDiagramBuilder.h
- src/triangulate/VoronoiDiagramBuilder.cpp
- src/triangulate/quadedge/QuadEdgeSubdivision.cpp
- tests/unit/capi/GEOSVoronoiDiagramTest.cpp
- tests/unit/triangulate/VoronoiTest.cpp
This may slow down the Voronoi creation process by a significant amount (50% for a diagram of 1 million random points), so it needs to be explicitly turned on through `VoronoiDiagramBuilder::setOrdered` or `GEOS_VORONOI_PRESERVE_ORDER`.
(This PR is an update of #320)
> Voronoi: Add option to reorder diagram to match order of input points

- NEWS.md
- include/geos/simplify/TaggedLineString.h
- include/geos/simplify/TaggedLineStringSimplifier.h
- src/simplify/TaggedLineString.cpp
- src/simplify/TaggedLineStringSimplifier.cpp
- src/simplify/TopologyPreservingSimplifier.cpp
- tests/unit/simplify/TopologyPreservingSimplifierTest.cpp
This PR is the topology-preserving equivalent of #773.
Resolves https://trac.osgeo.org/geos/ticket/1064
> TopologyPreservingSimplifier: Allow ring origin to be removed

- NEWS.md
- include/geos/geom/Envelope.h
- src/geom/Envelope.cpp
- tests/unit/capi/GEOSIntersectionTest.cpp
- tests/unit/capi/capi_test_utils.h
- tests/unit/geom/EnvelopeTest.cpp
This PR is an alternative approach to #790 that replaces comparison operators in `Envelope` with the C99 comparison functions that provide an equivalent result but do not set `FE_INVALID`.
@jorisvandenbossche 
In the process of putting this together I noticed that `Envelope::distance` sets `FE_INEXACT` in some of the test cases. I am guessing that one is not a problem for you?
> Avoid FE_INVALID on operations with empty Envelopes

- src/io/WKTWriter.cpp
- tests/unit/io/WKTWriterTest.cpp
These flags were omitted by design in https://trac.osgeo.org/geos/changeset/2998. I'm not sure what the motivation was for that. Including them makes GEOS output consistent with PostGIS.
Resolves https://trac.osgeo.org/geos/ticket/1129
> WKTWriter: Output dimension flags for empty geometries

- NEWS.md
- include/geos/operation/polygonize/EdgeRing.h
- include/geos/operation/polygonize/Polygonizer.h
- src/operation/polygonize/EdgeRing.cpp
- src/operation/polygonize/Polygonizer.cpp
- tests/unit/capi/GEOSPolygonizeTest.cpp
- tests/unit/operation/polygonize/PolygonizeTest.cpp
Fix from https://github.com/locationtech/jts/pull/949
Resolves https://github.com/libgeos/geos/issues/782
> Polygonizer: Fix duplicate results from getInvalidRingLines()

- include/geos/algorithm/distance/DiscreteHausdorffDistance.h
- include/geos/geom/CoordinateFilter.h
- include/geos/geom/CoordinateSequence.h
- include/geos/geom/Quadrant.h
- include/geos/util/UniqueCoordinateArrayFilter.h
- src/geom/CoordinateSequence.cpp
- src/index/chain/MonotoneChainBuilder.cpp
- src/noding/ScaledNoder.cpp
- src/operation/valid/RepeatedPointRemover.cpp
- src/precision/PrecisionReducerTransformer.cpp
- tests/unit/geom/CoordinateSequenceTest.cpp
- tests/unit/operation/valid/RepeatedPointRemoverTest.cpp
The interface of CoordinateFilter is changed so that a filter should support operations on CoordinateXY* rather than Coordinate*. By default, higher-dimension coordinates will default to base-class implementations (e.g., a CoordinateXYZM will be processed as a CoordinateXY if no implementation is available for Coordiante or CoordinateXYZM.)
To avoid the case where the filter implementation does not need to consider Z or M but must preserve them (e.g., repeated point removal), the CoordinateInspector and CoordinateMutator base classes are provided. These allow a filter class to inherit from the base using CRTP and provide a template for the filter method rather than an implementation for each coordinate type.
> CoordinateFilter: Support multiple CoordinateSequence dimensions

- .github/workflows/ci.yml
- CMakeLists.txt
- INSTALL.md
- NEWS.md
- examples/README.md
- include/geos/geom/CoordinateSequence.h
- include/geos/util.h
- src/geom/CoordinateSequence.cpp
- tests/unit/geom/CoordinateSequenceTest.cpp
- web/content/usage/download.md
As a follow-on to the introduction of XY, XYM and XYZM Coordinate types to GEOS, I have been exploring the feasibility of supporting these coordinate types in the overlay operations. Consistent with the new `CoordinateSequence` implementation, a design goal is to avoid a penalty for M values in cases where they are not used. (Good news: it's already working for simple cases such as line intersections).
One problem I have come across several times already is the need to perform some operation to each coordinate in a sequence, in type-generic but type-preserving way. For example, `OverlayMixedPoints::findPoints` needs to read a `CoordinateSequence`, find unique coordinates matching a certain condition that only requires use of X and Y, and write them to an output `CoordinateSequence`.
One …
> CoordinateSequence: Add type-detecting forEach (requires C++14)

- include/geos/shape/fractal/HilbertEncoder.h
- tests/unit/capi/GEOSMakeValidTest.cpp
In addition to [1]. Otherwise geos fails to build with: "geos-3.11.1/include/geos/shape/fractal/HilbertEncoder.h:40:28: error: expected ')' before 'p_level'
40 |     HilbertEncoder(uint32_t p_level, geom::Envelope& extent);
|                   ~        ^~~~~~~~
|                            )
/var/tmp/paludis/build/sci-libs-geos-3.11.1/work/geos-3.11.1/include/geos/shape/fractal/HilbertEncoder.h:41:5: error: 'uint32_t' does not name a type
41 |     uint32_t encode(const geom::Envelope* env);
|     ^~~~~~~~"
[1] 0e8d4368b8bd72a7d361286e8523ebce5cff6146
> Fix build with gcc 13 by including <cstdint>

- src/algorithm/CGAlgorithmsDD.cpp
- src/geom/LineSegment.cpp
- tests/unit/algorithm/distance/DiscreteHausdorffDistanceTest.cpp
- tests/unit/capi/GEOSVoronoiDiagramTest.cpp
Similarly as https://github.com/libgeos/geos/pull/790 / https://github.com/libgeos/geos/pull/791 and fixes the remaining cases originally reported in https://github.com/libgeos/geos/issues/515
> Avoid FE_INVALID floating point errors in HausdorffDistance and VoronoiDiagram

- NEWS.md
- capi/geos_c.cpp
- capi/geos_c.h.in
- capi/geos_ts_c.cpp
- include/geos/geom/CoordinateSequence.h
- include/geos/geom/Geometry.h
- include/geos/geom/GeometryCollection.h
- include/geos/geom/LineString.h
- include/geos/geom/Point.h
- include/geos/geom/Polygon.h
- src/geom/CoordinateSequence.cpp
- src/geom/GeometryCollection.cpp
- src/geom/LineString.cpp
- src/geom/Point.cpp
- src/geom/Polygon.cpp
- tests/unit/capi/GEOSEqualsIdenticalTest.cpp
- tests/unit/capi/GEOSIdenticalTest.cpp
- tests/unit/geom/CoordinateSequenceTest.cpp
This PR adds a C API function `GEOSIdentical` that determines if two geometries are ~binary-equivalent~ pointwise-equivalent. It is distinct from other predicates such as `GEOSEquals` (which uses topological equality, returning `true` for different representations of the same structure) and `GEOSEqualsExact` (which uses pointwise equality, but allows for a distance tolerance and ignores Z/M values). This also differs from the above functions in applying a test of binary equivalence (NaN = NaN) rather than numeric equality (NaN != NaN).
I think there may _also_ be a place for some kind of `GEOSEqualsExactDims(int dims, double tol)` function that allows you to specify which dimensions you're interested in, but for the common case of "tol = 0, dims = ALL" it is worthwhile to have a specific …
> Add GEOSEqualsIdentical C API function for checking binary equivalence

- capi/geos_c.h.in
- include/geos/operation/overlay/snap/GeometrySnapper.h
resolves #814 
This updates the docstrings of `GEOSSnap` and `GeometrySnapper` to better clarify behavior, especially regarding creation of invalid geometries.
> DOC: Update docstring of GEOSSnap / GeometrySnapper to clarify behavior

- include/geos/geom/GeometryFactory.h
- src/geom/GeometryFactory.cpp
- tests/unit/geom/GeometryFactoryTest.cpp
This is already the case for all types except `LinearRing`. Change the behavior for `LinearRing` and add tests for all types.
> GeometryFactory: Ensure empty geometries 2D by default

- include/geos/io/WKTWriter.h
- src/io/WKTWriter.cpp
- src/operation/buffer/BufferBuilder.cpp
- src/operation/buffer/BufferCurveSetBuilder.cpp
- tests/unit/io/WKTWriterTest.cpp
The removal of empty dimensions (JTS behavior) is still available by a flag that defaults to off.
Also fix a case in `BufferBuilder` where a geometry declared to be 2D was storing 3D coordinates. Correct output of this case depended on `WKTWriter` ignoring the declared dimensionality.
Resolves https://github.com/libgeos/geos/issues/808
> WKTWriter: Disable removal of empty dimensions

- NEWS.md
- src/triangulate/tri/Tri.cpp
Adds exceptions to `Tri` methods for invalid indexes.
Prevents the infinite looping of #754 (but does not fix the underlying cause).
> Add Tri invalid index exceptions

- capi/geos_c.h.in
- include/geos/algorithm/construct/LargestEmptyCircle.h
- src/algorithm/construct/LargestEmptyCircle.cpp
- tests/unit/algorithm/construct/LargestEmptyCircleTest.cpp
Enhances `LargestEmptyCircle` to allow boundaries to be any polygonal geometry.  The boundary may have any spatial relationship to the obstacles (containing, intersecting, or disjoint), or may be empty.
Port of part of https://github.com/locationtech/jts/pull/973
> Enhance LargestEmptyCircle boundary handling

- util/geosop/GeometryOp.cpp
- util/geosop/GeosOp.cpp
This adds 'hasZ' and 'hasM' operations, e.g.:
```bash
$ ./bin/geosop -a "POINT (1 2 3 4)" -f txt hasZ
true
$ ./bin/geosop -a "POINT M (1 2 4)" -f txt hasZ
false
```
Also, a few output options are improved. Firstly the precision option is fixed (it was effectively ignored):
```bash
$ ./bin/geosop -a "POINT (5.555 7.777)" -f wkt -p 2
POINT (5.55 7.78)
```
The output dimension is increased to 4 to show Z and or M ordinates:
```bash
$ ./bin/geosop -a "LINESTRING Z (0 0 10, 1 0 20)" -f wkt interpolate 0.5
POINT Z (0.5 0 15)
```
similar for hex-encoded WKB:
```bash
$ ./bin/geosop -a "POINT (1 2)" -f wkb
0101000000000000000000F03F0000000000000040
$ ./bin/geosop -a "POINT Z (1 2 3)" -f wkb
0101000080000000000000F03F00000000000000400000000000000840
$ ./bin/geosop -a "POINT M (1 2 4)" -f wkb …
```
> geosop: add 'hasZ' and 'hasM' operations; change output to show Z/M

- capi/geos_c.h.in
- src/io/WKTWriter.cpp
- tests/unit/io/WKTWriterTest.cpp
The WKTWriter Old3D option previously only modified the behaviour of XYZ geometries, rendering "POINT Z (1 2 3)" as "POINT (1 2 3)". This PR changes geometries with M coordinates to also remove dimensionality tag, as I suppose this was the original meaning of the option.
<s>For instance, "POINT M (1 2 4)" would be formatted as "POINT (1 2 4)". I've added a note that 3D XYZ and XYM geometries are indistinguishable.</s>
Furthermore, "POINT ZM (1 2 3 4)" is now formatted as "POINT (1 2 3 4)" with Old3D enabled. Is this the same output as older PostGIS versions?
> Change WKTWriter Old3D option to only add "M" for XYM

- capi/geos_c.h.in
- src/algorithm/Orientation.cpp
- tests/unit/capi/GEOSCoordSeqTest.cpp
Change behaviour of `Orientation.isCCW` and `GEOSCoordSeq_isCCW` to avoid throwing an exception when the input sequence is short (< 4 vertices).  This aligns with JTS semantics, and simplifies logic in internal routines.  In particular, `normalize` now works on invalid (short) rings without additional checks.
> Remove Orientation.isCCW exception

- include/geos/coverage/CoverageEdge.h
- include/geos/coverage/CoveragePolygonValidator.h
- include/geos/coverage/CoverageRingEdges.h
- include/geos/coverage/VertexRingCounter.h
- src/coverage/CoverageBoundarySegmentFinder.cpp
- src/coverage/CoverageEdge.cpp
- src/coverage/CoveragePolygonValidator.cpp
- src/coverage/CoverageRingEdges.cpp
- src/coverage/CoverageSimplifier.cpp
- src/coverage/VertexRingCounter.cpp
- tests/unit/coverage/CoverageRingEdgesTest.cpp
- tests/unit/coverage/CoverageSimplifierTest.cpp
- tests/unit/coverage/CoverageValidatorTest.cpp
Fixes `CoverageValidator` and `CoverageSimplifier` to handle cases with collapsed and empty components.
> Fix Coverage ops to handle empty and collapsed cases

- capi/geos_ts_c.cpp
References GH-873, avoid hard-to-trace errors.
> Throw exception on non-initialization rather than quiet failure, GH-873

- include/geos/algorithm/construct/MaximumInscribedCircle.h
- src/algorithm/construct/LargestEmptyCircle.cpp
- src/algorithm/construct/MaximumInscribedCircle.cpp
- tests/unit/algorithm/construct/LargestEmptyCircleTest.cpp
- tests/unit/algorithm/construct/MaximumInscribedCircleTest.cpp
This PR adds heuristics to MaximumInscribedCircle and LargestEmptyCircle to prevent long-running (and memory-intensive) processing for nearly flat and very thin inputs.
There are two problems solved:
* if the input extent is very small in one dimension (i.e. almost flat), the cell grid was initialized with cells of very small size, causing a memory explosion.  This is avoided by using a single initial grid cell covering the extent.
* Very thin (low-area) geometries (or LEC boundaries) cause a long search to find a cell with a centre inside the geometry (since very few cells in the search space satisfy this condition). A heuristic is used to determine a maximum number of iterations permitted. This means that the computed result may lie outside the input geometry. This can be mitigated by …
> Fix MaximumInscribedCircle and LargestEmptyCircle performance and memory issues

- include/geos/geom/CoordinateSequence.h
- src/geom/GeometryFactory.cpp
- src/geom/Point.cpp
- src/io/WKTWriter.cpp
While making a more strict approach to NaN coordinate handling in shapely, I noticed that the NaN handling (and coordseq dimensionality) has improved a great deal in GEOS (which is great!)
However I bumped into an inconsistency in the interpretation of XYZ points with NaN coordinates. When constructing a point from `NaN, NaN`, you get an empty point. I personally think that is good because it is consistent with the limitations of WKB. I guess the rule is "a point with an all-NaN coordinate is an empty point".
However, the logic in GEOS considers only X and Y at two points yielding surprising behaviour on 3D points:
```
>>> Point(nan, nan nan)
<POINT Z EMPTY>
>>> Point(nan, 1, nan)
<POINT Z (NaN 1 NaN)
>>> Point(nan, nan, 1)
<POINT Z EMPTY>
```
This PR addresses that issue by constructing …
> Construction of XYZ points with NaN coordinates

- NEWS.md
- capi/geos_c.cpp
- capi/geos_c.h.in
- capi/geos_ts_c.cpp
- tests/unit/capi/GEOSGeom_createCollectionTest.cpp
References #848. This does the opposite of collection creation, taking in a geometry, removing the subgeometries and returning them as a `GEOSGeometry**`. The caller remains on the hook for all the memory management, and the input geometry becomes an empty geometry, since it has lost its sub-geometries.
> Add GEOSGeom_releaseCollection to CAPI

- capi/geos_c.h.in
This is an update to clarify in documentation the behaviour of `GEOSCoverageUnion` when the input geometries don't meet the noding/overlap constraints.
> Clarify coverage union behaviour with unmet constraints

- NEWS.md
- capi/geos_ts_c.cpp
- tests/unit/capi/GEOSHasZMTest.cpp
This resolves an inconsistency between the C++ and C API versions of HasZ. Here is the correct answer with the C++ API version via geosop:
```bash
$ ./bin/geosop -a "POINT Z EMPTY" -f txt hasZ
true
```
but older CAPI implementations of GEOSHasZ short-circuited to return false if the geometry was empty. This was due to older handling of empty geometries, and possibly the wording "Tests whether the input geometry has Z coordinates" since empty geometries don't have any coordinates. But I think the C++ HasZ has it right.
Note that HasM was already consistent for C++ and C API, which has M with `POINT M EMPTY`. Tests are expanded for different coordinate types.
> CAPI: fix GEOSHasZ with empty geometries

- src/io/WKTReader.cpp
- tests/unit/io/WKTReaderTest.cpp
Closes #886
Also, re-word some comments around "deprecated" or "correct" forms for multipoint. I can't see any official source for the correct form. Looking at OGC 06-103r4 for [SFA](https://www.ogc.org/standard/sfa) 1.2.1 it has both:
- page 18: `multipoint m(1 0 4, 3 1 4, 5 3 4)`
- page LXI (aka 61): `MultiPoint ((10 10), (20 20))`
The BNF description implies the second form is more "correct". Both GEOS and PostGIS WKTWriters only write the first form, so there is not clear "correct" form.
Also note that this PR does not attempt to fix an outstanding issue with EMPTY described in #902.
> Fix reading MultiPoint Z/M WKT

- util/geosop/GeosOp.cpp
- util/geosop/GeosOp.h
This enhancement adds `-f geojson` (or `-f json`) to output GeoJSON from `geosop`.
```bash
$ ./bin/geosop -a "POINT(1.1 2.2)" -f geojson buffer 10.0
```
> `{"type":"Polygon","coordinates":[[[11.1,2.2],[10.907852804032304,0.2490967798387178],[10.338795325112867,-1.6268343236508978],[9.414696123025452,-3.3557023301960216],[8.171067811865475,-4.871067811865474],[6.655702330196023,-6.114696123025452],[4.9268343236508985,-7.038795325112868],[3.0509032201612833,-7.607852804032304],[1.1000000000000008,-7.8],[-0.8509032201612818,-7.607852804032304],[-2.726834323650897,-7.038795325112868],[-4.45570233019602,-6.114696123025454],[-5.971067811865474,-4.871067811865475],[-7.214696123025453,-3.3557023301960216],[-8.138795325112868,-1.6268343236508986],[-8.707852804032305,0.24909677983871403],[-8.9,2.199 …
> geosop: add option to output GeoJSON

- NEWS.md
- src/io/GeoJSONReader.cpp
- tests/unit/io/GeoJSONReaderTest.cpp
Closes #906
Notes:
- This fixes `main` only. To patch earlier releases see #910
- To enable 3D support, a great deal of GeoJSONReader would need to be re-written.
> GeoJSONReader: Fix 2D empty geometry creation

- NEWS.md
- capi/geos_c.h.in
- include/geos/io/WKBWriter.h
- tests/unit/capi/GEOSWKBWriterTest.cpp
- util/geosop/GeosOp.cpp
- web/content/specifications/wkb.md
This potentially breaking change is to use output dimension 4 with the WKBWriter.
For example, `POINT Z (1.1 2.2 3.3)` via writeHEX using defaults:
- Current: `01010000009A9999999999F13F9A99999999990140` or `POINT (1.1 2.2)`
- Proposed: `01010000809A9999999999F13F9A999999999901406666666666660A40` same as input WKT
Also add a few additional tests related to `setOutputDimension` that didn't seem to be covered.
> Change WKBWriter default output dimension to 4

- NEWS.md
- src/operation/intersection/RectangleIntersection.cpp
- tests/unit/capi/GEOSClipByRectTest.cpp
- tests/unit/operation/intersection/RectangleIntersectionTest.cpp
This seems to be an old bug, where `GEOSClipByRect("POINT EMPTY", ...)` raises:
> GEOSException: UnsupportedOperationException: getX called on empty Point"
Other empty combinations work fine (they only return `GEOMETRYCOLLECTION EMPTY`), so add each empty combination to the tests.
> GEOSClipByRect: Fix case with POINT EMPTY, add more tests

- capi/geos_ts_c.cpp
The lintian QA tool reported a spelling error for the Debian package build:
* unintialized -> uninitialized
> Fix spelling errors.

- src/geom/HeuristicOverlay.cpp
- tests/unit/geom/Geometry/differenceTest.cpp
Still "handles" mixed dim by dropping into old overlay, but works for many cases. Added test case to ensure we don't lose behaviour in this branch.
> Catch Mixed-Dimension case and handle

- capi/geos_c.cpp
- capi/geos_c.h.in
- include/geos/io/WKTWriter.h
- src/io/WKTWriter.cpp
This PR exposes the modified GEOS ryu-based double formatting functionality in the c-api, as well as as a static function on the WKTWriter. The change itself is pretty small, but I also ran the bundled `astyle` on the modified files which seems to have formatted lots of other lines. Let me know if you want me to undo it.
> Expose geos ryu fork

- CMakeLists.txt
- HOWTO_RELEASE
This PR uses [CPACK_VERBATIM_VARIABLES](https://cmake.org/cmake/help/latest/module/CPack.html#variable:CPACK_VERBATIM_VARIABLES) to simplify the escapes with the `CPACK_SOURCE_IGNORE_FILES` list for CPack. A new entry is added to ignore all files/directories that start with '`.`'. Only a few items that start with '`.`' are removed, otherwise the list is alphasorted.
Looking at results from `cmake --build . --target dist`, the only differences is that `.astylerc`, `.editorconfig` and `.mailmap` are now ignored.
Also fix HOWTO_RELEASE to the current main repo.
> CPack: ignore other files/dirs starting with .; use verbatim option

- capi/geos_c.h.in
- include/geos/algorithm/construct/IndexedDistanceToPoint.h
- include/geos/algorithm/construct/IndexedPointInPolygonsLocator.h
- include/geos/algorithm/construct/LargestEmptyCircle.h
- include/geos/geom/util/PolygonalExtracter.h
- src/algorithm/construct/IndexedDistanceToPoint.cpp
- src/algorithm/construct/IndexedPointInPolygonsLocator.cpp
- src/algorithm/construct/LargestEmptyCircle.cpp
- src/geom/util/PolygonalExtracter.cpp
- tests/unit/algorithm/construct/LargestEmptyCircleTest.cpp
- tests/unit/capi/GEOSLargestEmptyCircleTest.cpp
- tests/unit/capi/GEOSMaximumInscribedCircleTest.cpp
- tests/unit/capi/capi_test_utils.h
Fixes LargestEmptyCircle to handle polygonal obstacles. The centre of the LEC is constrained to be outside of any polygonal obstacles. Previously polygonal obstacles were only handled as linear constraints, which allowed the LEC centre to lie inside polygons.
Port of https://github.com/locationtech/jts/pull/988
> Add LargestEmptyCircle handling of polygon obstacles

- capi/geos_ts_c.cpp
The defect is detected by coverity scan. The detailed info is following:
```
*** CID 416530:  Null pointer dereferences  (FORWARD_NULL)
/root/pxiao/TDengine/contrib/geos/capi/geos_ts_c.cpp: 2075 in GEOSGeom_releaseCollection_r::[lambda() (instance 1)]::operator ()() const()
2069                 GeometryCollection *col = dynamic_cast<GeometryCollection*>(collection);
2070                 if (!col) {
2071                     handle->ERROR_MESSAGE("Parameter collection of GEOSGeom_releaseCollection_r must not be a collection");
2072                 }
2073     
2074                 // Early exit on empty/null input
>>>     CID 416530:  Null pointer dereferences  (FORWARD_NULL)
>>>     Passing null pointer "col" to "getNumGeometries", which dereferences it. (The dereference happens because …
```
> fix: null pointer deref on col

- CMakeLists.txt
Avoid setting CMAKE_BUILD_TYPE default when multi-config generators are used.
Avoid setting CMAKE_BUILD_TYPE STRINGS property if it is not a cache variable. This avoids CMake errors if CMAKE_BUILD_TYPE isn't set on the command-line.
Closes #932
> Fix CMake on Windows with Visual Studio

- capi/geos_c.h.in
- include/geos/geom/Geometry.h
This addresses both C++ and C API docs. Further suggestions are welcome.
Closes #949
> Doc: describe empty geometry for getNumGeometries

- web/data/menu/more.yaml
View Source on home page https://libgeos.org/  points to postgis
> fix View Source link on home page (points to postgis)

- src/geom/prep/PreparedLineStringDistance.cpp
- src/operation/distance/IndexedFacetDistance.cpp
- tests/unit/capi/GEOSPreparedDistanceTest.cpp
- tests/unit/capi/GEOSPreparedDistanceWithinTest.cpp
- tests/unit/operation/distance/IndexedFacetDistanceTest.cpp
- tests/unit/utility.h
This PR fixes `PreparedLineStringDistance` to handle the cases:
1. the prepared line is contained within the envelope of the test geometry
2. the prepared line is contained within a polygonal geometry
Fixing the first situation requires removing an invalid heuristic check from `IndexedFacetDistance.isWithinDistance` [code](https://github.com/libgeos/geos/blob/main/src/operation/distance/IndexedFacetDistance.cpp#L69):
```
auto env2 = g->getEnvelope();
if (distance(env2.get()) > maxDistance) {
return false;
}
```
The check attempts to short-circuit the withinDistance test by checking the distance to the envelope polygon of the tested geometry. However, `IndexedFacetDistance` only computes distances to linework, not to polygonal geometries. So the test is incorrect in some cases (such as …
> Fix PreparedLineStringDistance for lines within envelope and polygons

- capi/geos_ts_c.cpp
- include/geos/geom/PrecisionModel.h
- src/geom/PrecisionModel.cpp
- tests/unit/capi/GEOSGeom_setPrecisionTest.cpp
`GEOS_setPrecision` accepts a parameter specifying the **grid size** of the desired precision.  The most common usage is to reduce the number of decimal places in a geometry (e.g. to 3 decimal places).  In this case, the grid size is a negative power of 10 (e.g. 0.001).  However, this can result in inexact rounding of ordinate values.
For example, this `geosop` command reproduces this [PostGIS issue](https://trac.osgeo.org/postgis/ticket/5520#comment:2) and shows how reducing the precision of a geometry using grid size 0.001 produces unwanted "extra decimals" (note that in `geosop` the `reducePrecision` operation parameter is negative to indicate the value is a grid size):
```
bin/geosop -a "LINESTRING (657035.913 6475590.114,657075.57 6475500)" reducePrecision N-0.001
LINESTRING …
```
> Improve scale handling for GEOS_setPrecision

- tests/unit/operation/overlayng/PrecisionReducerTest.cpp
Issue #811 is caused by a bug in a [CoordinateSequence::add](https://github.com/libgeos/geos/blob/main/src/geom/CoordinateSequence.cpp#L178) method, which is called from [SegmentNodeList.addEdgeCoordinates](https://github.com/libgeos/geos/blob/main/src/noding/SegmentNodeList.cpp#L313) during snap-rounding noding.  #963 fixes this issue.  
This PR adds a unit test using the case in #811.
If the original code is used with the debug trace statements in [SegmentNodeList.addEdgeCoordinates](https://github.com/libgeos/geos/blob/main/src/noding/SegmentNodeList.cpp#L313), the test:
```
bin/test_geos_unit geos::operation::overlayng::PrecisionReducer 15
```
produces:
```
addEdgeCoordinates: (127.117461568 34.562519572, 127.117461568 34.562519572)
updated coord list: (127.117461568 34.562519572) …
```
> Add PrecisionReducer test for CoordinateSequence.add bug

- NEWS.md
- capi/geos_c.h.in
- src/io/WKTWriter.cpp
- tests/unit/capi/GEOS_printDoubleTest.cpp
- tests/unit/io/WKTWriterTest.cpp
This PR modifies how big and small values are formatted by WKTWriter by switching from [positional](https://en.wikipedia.org/wiki/Positional_notation) to [scientific notation](https://en.wikipedia.org/wiki/Scientific_notation) where necessary, to avoid rounding to zero or overflowing a char buffer crash.
This somewhat expands the "trim" mode definition to mean "print pretty numbers" since it doesn't always honour (e.g.) "3" to show fixed millimetre precision, since it will use scientific notation to show smaller non-zero numbers if necessary. The non-trim mode still uses fixed notation, and will show (e.g.) "-0" in some cases.
Also the char buffer used for these numbers is reduced from 128 to 28.
Some new unit tests are added for `GEOS_printDouble` from the CAPI. Other unit tests check …
> Refactor WKTWriter::writeTrimmedNumber for big and small values

- src/algorithm/InteriorPointPoint.cpp
- tests/xmltester/tests/general/TestInteriorPoint.xml
Fix `InteriorPointPoint` to handle empty elements (e.g. `MULTIPOINT((0 0), EMPTY)`).
Fixes #976.
Original report in https://trac.osgeo.org/postgis/ticket/5595
> Fix InteriorPointPoint to handle empty elements

- src/algorithm/PointLocator.cpp
- src/geomgraph/GeometryGraph.cpp
- tests/xmltester/tests/general/TestRelatePA.xml
This is a port of https://github.com/locationtech/jts/pull/1015.  It improves the `RelateOp` algorithm to handle EMPTY elements better in general.
Fixes #988.
> Fix spatial predicates for MultiPoint with EMPTY

- util/geosop/cxxopts.hpp
illumos' implementation of stdint.h treats chars as int8_t. So when I was trying to compile this on an illumos distro I was getting the following compilation error:
```
/usr/local/src/geos-3.12.0/util/geosop/cxxopts.hpp:793:10: error: redefinition of 'void cxxopts::values::parse_value(const string&, char&)'
793 |     void parse_value(const std::string& text, char& c)
|          ^~~~~~~~~~~
/usr/local/src/geos-3.12.0/util/geosop/cxxopts.hpp:682:5: note: 'void cxxopts::values::parse_value(const string&, int8_t& ' previously defined here
682 |     parse_value(const std::string& text, int8_t& value)
|     ^~~~~~~~~~~
```
So this change will only add one of the functions if it's an illumOS system.
> Added illumos macro for int8_t parse_value override. 

- web/content/usage/install.md
I suggest it is replaced with https://packages.ubuntu.com/kinetic/software-properties-common
python3-software-properties may be preferrable (less to download) but I've not tested it.
https://packages.ubuntu.com/kinetic/python3-software-properties
> python-software-properties has been deprecated

- src/geom/CoordinateSequence.cpp
- tests/unit/geom/CoordinateSequenceTest.cpp
Logic error only causes an incorrect result when GEOS_COORDSEQ_PADZ is not defined.
Fixes https://github.com/libgeos/geos/issues/997
> CoordinateSequence: Fix logic error when adding XYM seq to XYZ seq

- include/geos/algorithm/distance/DiscreteHausdorffDistance.h
- src/algorithm/distance/DistanceToPoint.cpp
- tests/unit/algorithm/distance/DiscreteHausdorffDistanceTest.cpp
Fix regression in `DiscreteHausdorffDistance` to handle `LinearRing`s.
Fixes #987
> Fix DiscreteHausdorffDistance for LinearRing

- include/geos/io/GeoJSON.h
- src/io/GeoJSON.cpp
- src/io/GeoJSONReader.cpp
- src/io/GeoJSONWriter.cpp
- tests/unit/io/GeoJSONReaderTest.cpp
- tests/unit/io/GeoJSONWriterTest.cpp
1. Add id and getter for GeoJSONFeature
2. Modify the copy constructor of GeoJSONFeature
3. Check "id" in GeoJSONReader
4. Check "id" in GeoJSONWriter
5. Modify unit test for id
> Support id for GeoJSONFeature

- src/operation/valid/IsSimpleOp.cpp
- tests/xmltester/tests/general/TestSimple.xml
Fixes `IsSimpleOp` to handle `MultiPoint`s with empty elements.
Reported in https://trac.osgeo.org/postgis/ticket/5628
> Fix IsSimpleOp for MultiPoint with empty element

- src/geom/prep/AbstractPreparedPolygonContains.cpp
- tests/unit/geom/prep/PreparedGeometryTest.cpp
Fixes the Prepared Polygon Contains predicate for the case of a GeometryCollection containing a single MultiPoint with multiple elements.
```
bin/geosop -a "MULTIPOLYGON(((-60 -50,-70 -50,-60 -40,-60 -50)))" -b "GEOMETRYCOLLECTION(MULTIPOINT((-60 -50),(-63 -49)))" containsPrep
==> true
```
Fixes #1007.
> Fix PreparedPolygonContains for GeometryCollection with MultiPoint

- capi/geos_c.cpp
- capi/geos_ts_c.cpp
Currently building with GCC link-time-optimization with -flto -Wodr leads to the following type of warnings:
```
/home/even/geos/geos/build_cmake/capi/geos_c.h:665:31: warning: ‘GEOSBufferWithParams_r’ violates the C++ One Definition Rule [-Wodr]
665 | extern GEOSGeometry GEOS_DLL *GEOSBufferWithParams_r(
|                               ^
/home/even/geos/geos/capi/geos_ts_c.cpp:4034:5: note: type mismatch in parameter 3
4034 |     GEOSBufferWithParams_r(GEOSContextHandle_t extHandle, const Geometry* g1, const BufferParameters* bp, double width)
|     ^
/home/even/geos/geos/capi/geos_ts_c.cpp:4034:5: note: type name ‘geos::operation::buffer::BufferParameters’ should match type name ‘GEOSBufParams_t’
/home/even/geos/geos/capi/geos_ts_c.cpp:4034:5: note: ‘GEOSBufferWithParams_r’ was …
```
> geos_c.cpp: fix declarations to avoid C++ One Definition Rule violations

- NEWS.md
- src/io/StringTokenizer.cpp
- tests/unit/io/WKTReaderTest.cpp
This fixes `StringTokenizer::peekNextToken` so that both `(EMPTY` and `( EMPTY` are `StringTokenizer::TT_WORD`.
The issue was that the second assignment of `pos` (from `str.find_first_of`) was less than the first (from `str.find_first_not_of`), meaning that it started searching from the wrong position. The fix is simply to set the starting position to `pos + 1`.
Closes #1013
> Fix StringTokenizer::peekNextToken

- src/coverage/CoverageSimplifier.cpp
- tests/unit/coverage/CoverageSimplifierTest.cpp
> Fix segfault when coverage simplify called with nonpolygons

- .github/workflows/ci.yml
Cf https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/
> CI: increase -j to take into account that recently GitHub action workers have bumped to 4 vCPUs

- .github/workflows/codeql.yml
We've added this guy recently in GDAL, PROJ and MapServer. I've given it a try in my rouault/geos fork and it found zero issues... ( https://github.com/rouault/geos/security/code-scanning?query=is%3Aopen+branch%3Aci_codeql+ ). Which is both a bit surprising (I had to fix hundreds in GDAL), and expected (GEOS shouldn't do anything dangerous).
Not sure how much appetite there is to add this here. Adding it will increase the GEOS score on https://securityscorecards.dev/viewer/?uri=github.com/libgeos/geos (SAST category)
> CI: add CodeQL static analyzer

- NEWS
- src/geom/HeuristicOverlay.cpp
- tests/unit/capi/GEOSDifferenceTest.cpp
This fixes a regression in the 3.9 branch (only the 3.9.5 release), which permits overlay ops GEOSDifference with mixed-type GeometryCollection inputs. It more-or-less reverts ad62ddf5d97beecc193756c99f6c076963d36536 but limits the caught exception to `geos::util::IllegalArgumentException`.
The added CAPI test passes on newer branches too (with some mods), and I'll possibly add this test into other branches after this PR looks good.
Closes #1023
---
There's just one outstanding thing that I don't fully understand. By design, the low-level C++ level does not support overlay ops with mixed GeometryCollection types. But it doesn't appear to be consistent, e.g. (here "GC" is a mixed GeometryCollection and "PT" is a Point):
- GC.difference(PT) // raises IllegalArgumentException
- …
> Fix overlay op regression with mixed GeometryCollection on 3.9 branch

- web/content/usage/c_api.md
in the example we have more x coordinates than y coordinates which could be slightly confusing to the most pedantic of readers. i've removed the extra x to match the code example below it.
thanks for the wonderfully useful/pervasive library!
> fix typo for clarity on GEOSCoordSeq_copyFromBuffer docs

- include/geos/geom/LineSegment.h
- include/geos/operation/buffer/BufferCurveSetBuilder.h
- src/operation/buffer/BufferCurveSetBuilder.cpp
- tests/unit/geom/LineSegmentTest.cpp
- tests/unit/operation/buffer/BufferOpTest.cpp
This fixes the `BufferCurveSetBuilder.isRingCurveInverted` check to avoid removing a class of raw offset curves which are in fact valid buffer curves. 
The check was introduced in https://github.com/locationtech/jts/pull/706 and improved in https://github.com/locationtech/jts/pull/878 (ported as https://github.com/libgeos/geos/commit/85ead60acc547328217f41d1be3d721e24753300).  But the issues reported in #984 revealed that there were still valid cases being removed incorrectly.
Fixes #984
> Fix buffer Inverted Ring Removal check

- CMakeLists.txt
With those tunings (mostly forcing -fno-fast-math), build passes without warnings with ICC 2024.0.2.29 in Release mode, and tests pass as well.
> CMakeLists.txt: add compatibility with latest Intel Compiler

- include/geos/geom/LineSegment.h
- tests/unit/capi/GEOSDensifyTest.cpp
- tests/unit/capi/capi_test_utils.h
New vertices created by GEOSDensify set Z coordinate to NAN, even if the original geometry has a valid Z.
This PR resolves the issue.
> GEOSDensify: Interpolate Z coordinate

- src/geom/IntersectionMatrix.cpp
- tests/unit/capi/GEOSRelatePatternMatchTest.cpp
- tests/unit/capi/GEOSRelatePatternTest.cpp
Fixes https://github.com/libgeos/geos/issues/1084
> IntersectionMatrix: Ignore patterns longer than 9 characters

- src/operation/intersection/RectangleIntersection.cpp
- tests/unit/capi/GEOSClipByRectTest.cpp
For [multi]linestrings/linerings, Z coordinate is interpolated from that of the nearest existing vertices.
For [multi]polygons, Z coordinate of points created on the boundary is interpolated as above.  For interior points, however, it is populated using the ElevationModel.
> GEOSClipByRect: preserve Z coordinate

- include/geos/coverage/CoveragePolygon.h
- include/geos/coverage/CoveragePolygonValidator.h
- include/geos/coverage/CoverageRing.h
- src/coverage/CoveragePolygon.cpp
- src/coverage/CoveragePolygonValidator.cpp
- src/coverage/CoverageRing.cpp
Improves the performance of CoveragePolygonValidator and CoverageValidator by adding logic to avoid testing sections of ring vertices if the entire section does not overlap the target adjacent polygon.
Port of https://github.com/locationtech/jts/pull/1053
Statistics: 323 geometries, 329,373 polygons, 459,540 vertices
Old code: 1579 ms
New code: 400 ms
Statistics: 323 geometries, 319,646 polygons, 27,706,942 vertices
Old code: 5308 s
New code: 59 s
> Add CoveragePolygonValidator section performance optimization

- .github/workflows/ci.yml
The main goal of this PR is to enable ccache for MSVC. According to the [docs](https://cmake.org/cmake/help/latest/prop_tgt/LANG_COMPILER_LAUNCHER.html) this can only be enabled for Makefile and Ninja generators, so this PR also switches the MSVC runs to install and use Ninja. While this seems to work, it does repeat a message for each object compilation:
> cl : Command line warning D9025 : overriding '/W3' with '/W4'
This could potentially be resolved at a later time with [CMP0092](https://cmake.org/cmake/help/latest/policy/CMP0092.html).
---
There are also many other minor changes in this PR:
- Show ccache stats at bottom of each build task, to show "hits" and other metrics. A few newer versions also accept `--verbose` to show directory info too (older versions raise errors, so don't …
> CI: show ccache stats, use Ninja for MSVC, misc. reformat

- include/geos/algorithm/LineIntersector.h
- tests/unit/capi/GEOSIntersectionTest.cpp
Fixes https://github.com/libgeos/geos/issues/1074
> LineIntersector: Fixed invalid read on mixed-dimensionality inputs

- include/geos/constants.h
- include/geos/coverage/CoverageRingEdges.h
- include/geos/geom/Geometry.h
- include/geos/operation/buffer/BufferOp.h
- include/geos/operation/buffer/OffsetCurveSection.h
This commit resolves issues with building GEOS in C++23 language mode (both -std=c++23 and -std=gnu++23 are supported). 
In particular, this resolves the following issues:
1. https://github.com/libgeos/geos/issues/1120
2. https://github.com/libgeos/geos/issues/1121
> fix building in C++23 language mode

- src/algorithm/construct/MaximumInscribedCircle.cpp
This fixes an issue with `MaximumInscribedCircle::computeMaximumIterations` that sometimes returns bogus values.
For example, with [this example](https://github.com/libgeos/geos/blob/6201229a66ae3eef2b0c62cc39dbab48b2e3df7e/tests/unit/algorithm/construct/LargestEmptyCircleTest.cpp#L333-L343) the number of iterations is needed by [`LargestEmptyCircle::compute()`](https://github.com/libgeos/geos/blob/4907d593aa6aa31c25dbe73933bf66995a04e498/src/algorithm/construct/LargestEmptyCircle.cpp#L235). The geometry calculates ncells=0.0903549, which would normally have a log value -2.40401. But the early cast to `size_t` doesn't correctly handle negative values meaning the maxIter is either 0 or 4294965296 (i.e. it's up to the compiler to decide). This fix will re-establish the maxIter to 4000 for …
> Fix MaximumInscribedCircle::computeMaximumIterations for small values

- .github/workflows/ci.yml
A few weeks ago I made some changes to the MSVC CI tests, replacing MSBuild with Ninja (#1118). While this adds speed, it looses coverage, so it would be worth re-adding. Also, it seemed that Ninja+Debug did not allow ccache to work.
This PR also adds some matrix items for MSVC Ninja build, adding one for 32-bit MSVC (which has one test failure #1129), and also a range of different MSVC versions and CXX standards.
One big caveat about using ccache is that compiler warnings are sometimes not shown, since it skips normal compiler processing if a cache is available. So there is value in periodically clearing the cache to see full CI logs.
This PR does not fix the repeated warning "cl : Command line warning D9025 : overriding '/W3' with '/W4'", as this may require some CMake modifications, …
> CI: re-add MSBuild as a separate job, use matrix for ninja builds

- .github/workflows/ci.yml
- CMakeLists.txt
This PR does the following:
- Sets CMake 3.15 as the minimum version
- Cleans up some old logic used to support older version of CMake 
- Updates CI testing with a range of versions 3.15 to 3.29
Some rationale for upgrading CMake versions:
- MSVC with Ninja builds repeat "cl : Command line warning D9025 : overriding '/W3' with '/W4'", which makes seeing "real" warnings difficult. This is the same issue and fix described with #936. See [policy CMP0092](https://cmake.org/cmake/help/latest/policy/CMP0092.html), which was attempted with 1df959cc8a39807e63a09bff6953ef43d434ccbf, but it seems to only take effect with `cmake_minimum_required(VERSION 3.15)`, thus the message finally goes away!
- CMake 3.15 is over 5 years old, released [July 17, …
> Establish minimum CMake version 3.15

- include/geos/noding/SegmentSetMutualIntersector.h
- tests/unit/coverage/CoverageSimplifierTest.cpp
This PR addresses two MSVC warnings (only shown in developer mode; e.g. see [previous build logs](https://github.com/libgeos/geos/actions/runs/10425205367/job/28875593065)):
- 22 instances of [C4275](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-2-c4275): non dll-interface class 'geos::noding::SegmentSetMutualIntersector' used as base for dll-interface class 'geos::noding::MCIndexSegmentSetMutualIntersector'. The fix is to add `GEOS_DLL` to `SegmentSetMutualIntersector`
- 1 instance of [C4101](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4101): warning C4101: 'iae': unreferenced local variable. The fix is to remove the unused variable.
This does not currently fix:
- 2 instances of …
> Add SegmentSetMutualIntersector for dll-interface class and other MSVC warnings

- include/geos/io/GeoJSONWriter.h
- src/io/GeoJSONReader.cpp
- src/io/GeoJSONWriter.cpp
- tests/unit/io/GeoJSONReaderTest.cpp
- tests/unit/io/GeoJSONWriterTest.cpp
This PR adds 3D (Z) coordinates support to GeoJSON reader and writer.
It includes a new method `setOutputDimensions` for the writer, similar to the WKT one, but which (for now ?) only accepts values 2 or 3. Support for M coordinates was left out of this PR as it is discouraged by the specification, and would require more thinking about special cases. Any M values in the coordinates being serialized are therefore ignored (like the Z values were before this PR).
Considering the handling of mixed 2D/3D coordinates and NaN values isn't clearly specified, I made some decisions in that regard which are of course all open for debate:
- Mixed coordinates are allowed. If a coordinate sequence contains any Z value, the missing coordinates in the parsed geometry will be `NaN`.  This behavior is …
> Add 3D coordinates supports to GeoJSON reader and writer

- CMakeLists.txt
- capi/geos_ts_c.cpp
- include/geos/algorithm/hull/HullTriangulation.h
- include/geos/geomgraph/DirectedEdge.h
- include/geos/geomgraph/Edge.h
- include/geos/geomgraph/EdgeEnd.h
- include/geos/geomgraph/EdgeEndStar.h
- include/geos/geomgraph/EdgeIntersection.h
- include/geos/geomgraph/EdgeIntersectionList.h
- include/geos/geomgraph/EdgeList.h
- include/geos/geomgraph/EdgeNodingValidator.h
- include/geos/geomgraph/EdgeRing.h
- include/geos/geomgraph/GeometryGraph.h
- include/geos/geomgraph/GraphComponent.h
- include/geos/geomgraph/Label.h
- include/geos/geomgraph/Node.h
- include/geos/geomgraph/NodeFactory.h
- include/geos/geomgraph/NodeMap.h
- include/geos/geomgraph/PlanarGraph.h
- include/geos/operation/relate/RelateNode.h
- include/geos/precision/PointwisePrecisionReducerTransformer.h
- src/geomgraph/EdgeList.cpp
- src/geomgraph/NodeMap.cpp
- src/operation/overlayng/OverlayPoints.cpp
- src/operation/relate/RelateComputer.cpp
- util/geosop/GeosOp.cpp
On top of PR #1138 
The removal of the useless virtual qualifiers is safe since the addition of -Wsuggest-override in a previous commit makes sure that all overloaded methods (of methods that ware marked as 'virtual') are marked as 'override', which in turns ensures that all base methods that are overriden are marked as 'virtual'.
(This doesn't change the status quo if a method was overloaded, but the base class lacked a 'virtual' and the overloaded method lacked a 'override'...)
Said otherwise, the dangerous situation would be a
```cpp
class A { virtual void foo(); };
class B: public A { virtual void foo(); };
```
where we would erroneously remove the virtual qualifier.
But given -Wsuggest-override, the above code would have been corrected to
```cpp
class A { virtual void foo(); };
class …
```
> include/geos/geomgraph: remove useless virtual qualifiers, add final and improve a bit const safety

- src/io/GeoJSONReader.cpp
- tests/unit/io/GeoJSONReaderTest.cpp
Forgot a small change in the initial PR, that made parsing MultiLineStrings ignore the Z coordinate.
> FIX: 3D coordinates handling of GeoJSON MultiLineString

- capi/geos_c.cpp
- capi/geos_c.h.in
- capi/geos_ts_c.cpp
- tests/unit/capi/GEOSGeom_transformXYZTest.cpp
This PR adds `GEOSGeom_transformXYZ`. Code is copied from `GEOSGeom_transformXY` by simply adding a `z` parameter to the callback function. Tests and documentation have been updated.
> Add GEOSGeom_transformXYZ

- include/geos/geom/CompoundCurve.h
- src/geom/CompoundCurve.cpp
- tests/unit/geom/CompoundCurveTest.cpp
- tests/unit/io/WKTWriterTest.cpp
Resolves https://github.com/libgeos/geos/issues/1103
> CompoundCurve: Add validateConstruction method

- CMakeLists.txt
As titled, this bumps our floor to C++17. It is proposed to implement this for GEOS 3.14+, not GEOS 3.13, which is expected soon.
The [C++11 RFC](https://libgeos.org/project/rfcs/rfc05/) has this comment:
> Is there a plan to upgrade to C++14 or C++17 to allow use of the C++ latest features? No, there is no plan. It is, however, recognized, such motion may be put to the vote around 2020.
I think that given we are near the end of 2024, it's time to finally increment. I don't think it requires an RFC due to us lagging the increment of many other projects and compilers on the systems that GEOS is used on. It was the C++11 increment that was disruptive and C++17 is not expected to be this late in the cycle.
> Bump minimum C++ standard to 17

- include/geos/operation/relateng/TopologyPredicate.h
> TopologyPredicate.h: add missing ostream inclusion

- include/geos/operation/relateng/TopologyPredicate.h
While building in Visual Studio for msvc141 we get build error "C2679: binary '<<': no operator found which takes a right-hand operand of type 'std::string' (or there is no acceptable conversion)"
This can be fixed by including the "string" header.
```
1>C:\geos\geos-3.13.0\dist\include\geos/operation/relateng/TopologyPredicate.h(200): error C2679: binary '<<': no operator found which takes a right-hand operand of type 'std::string' (or there is no acceptable conversion)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\ostream(508): note: could be 'std::basic_ostream<char,std::char_traits<char>> &std::basic_ostream<char,std::char_traits<char>>::operator <<(std::basic_streambuf<char,std::char_traits<char>> *)'
1>C:\Program Files …
```
> Update TopologyPredicate.h to include <string> header

- include/geos/edgegraph/MarkHalfEdge.h
- include/geos/geom/prep/PreparedLineStringDistance.h
- include/geos/geom/prep/PreparedLineStringNearestPoints.h
- include/geos/linearref/LocationIndexedLine.h
- include/geos/operation/relateng/EdgeSetIntersector.h
- include/geos/operation/union/CascadedPolygonUnion.h
- include/geos/operation/union/PointGeometryUnion.h
- include/geos/triangulate/polygon/PolygonHoleJoiner.h
- include/geos/triangulate/polygon/PolygonNoder.h
- include/geos/triangulate/tri/TriEdge.h
Verified with
``find include -name "*.h" -exec g++ -c {} -Iinclude -DUSE_UNSTABLE_GEOS_CPP_API \;``
> Fixes to make sure each header can be compiled in a standalone way

- benchmarks/index/chain/MonotoneChainPerfTest.cpp
A single line edit to fix a warning (that is turnde into an error) from GCC when building with -DBUILD_BENCHMARKS=ON.
> Add override specifier in MonotoneChainPerfTest to avoid GCC warning.

- include/geos/geom/CoordinateSequence.h
- src/geom/SimpleCurve.cpp
- src/operation/BoundaryOp.cpp
- tests/unit/capi/GEOSBoundaryTest.cpp
- tests/unit/capi/capi_test_utils.h
Add an `applyAt` method to make it simpler to get the correct `Coordinate` type from a sequence and pass it to a function.
> CoordinateSequence: Add applyAt method

- .codespellrc
- .github/workflows/ci.yml
- NEWS.md
- include/geos/geom/Geometry.h
- include/geos/geom/Surface.h
- include/geos/io/WKTWriter.h
- include/geos/noding/IteratedNoder.h
- include/geos/operation/overlayng/OverlayUtil.h
- include/geos/planargraph/DirectedEdge.h
- include/geos/vend/json.hpp
- src/algorithm/InteriorPointArea.cpp
- src/algorithm/MinimumBoundingCircle.cpp
- src/geom/Point.cpp
- src/geomgraph/Edge.cpp
- src/index/bintree/NodeBase.cpp
- src/operation/buffer/BufferCurveSetBuilder.cpp
- src/operation/relate/RelateComputer.cpp
- src/operation/relateng/RelateNG.cpp
- src/operation/relateng/TopologyComputer.cpp
- tests/unit/capi/GEOSGeom_transformXYZTest.cpp
- tests/unit/geom/util/GeometryFixerTest.cpp
- tests/xmltester/tests/general/TestPreparedPolygonPredicate.xml
- tools/codespell.ignore
- web/content/posts/2024-08-13-relateng.md
- web/content/posts/2024-09-06-geos-3-13-released.md
- web/content/usage/tools.md
Following on #1128, this PR fixes a few more typos (some from me).
It also adds configuration to enable CI to run `codespell` to catch them before they get in. Third-party tools should be ignored, as is done with the configuration.
False-positive words to ignore can be added to `tools/codespell.ignore`.
> Fix typos, add CI job to help catch them

- include/geos/operation/relateng/RelateGeometry.h
- src/operation/relateng/TopologyComputer.cpp
- tests/unit/operation/relateng/RelateNGGCTest.cpp
- tests/xmltester/tests/general/TestRelateGC.xml
Improve the `RelateNG` self-noding check to allow A-L cases to take advantage of prepared predicates.
Previously, A/L cases were not using the prepared noder cache for predicates which require self-noding (such as `contains`, `covers`, `relate` etc). This caused significantly poor performance for a common situation. The self-noding check has been refined to allow A/L cases to be use the cached noder.
This makes `RelateNG` in prepared mode as fast as `PreparedGeometry` for all cases (and it handles more cases).
Port of https://github.com/locationtech/jts/pull/1099
For example, a test in `perf_topo_predicate` has dramatically reduced execution time (133x faster):
```
16001, 961, 759, LineString, 101, RelateOp - contains, 221629, 1.0
16001, 961, 759, LineString, 101, Geometry - contains, …
```
> Improve RelateNG performance for A/L cases in prepared predicates

- CMakeLists.txt
Use an absolute path to be more sure that the path is correct
> Update CMakeLists.txt to use absolute path

- .gitignore
I am building a package that includes geos as a dependency, with compilation targeting Python, and builds happening with ``scikit-build-core``. I had a mysterious build failure for missing files in the ``cmake`` folder inside the build folder when built with ``pipx run build``, and tracked down the problem to the fact that the build runs a git clean and doesn't copy over files that are ignored by ``.gitignore``. Fixing that (as in this PR), allowed that part of the build to work properly. I think this change is harmless since there are already ``.cmake`` files in the repo so they should probably not be in the ``.gitignore`` anyhow.
> Update .gitignore to remove *.cmake

- src/io/GeoJSONWriter.cpp
- tests/unit/io/GeoJSONWriterTest.cpp
GeoJSONWriter will throw exception when handle these two cases:
```json
{
"type": "Feature",
"geometry": {
"type": "Point",
"coordinates": [ 0, 0 ]
},
"properties": {
"matrix": [
[ 1, 2, 3 ],
[ 4, 5, 6 ]
]
}
}
```
```json
{
"type": "Feature",
"geometry": {
"type": "Point",
"coordinates": [ 0, 0 ]
},
"properties": {
"array": [
{ "key": "value_1" },
{ "key": "value_2" }
]
}
}
```
the message of the exception is :
```text
cannot use operator[] with a string argument with array
```
The root cause is here:
https://github.com/libgeos/geos/blob/3.13.0/src/io/GeoJSONWriter.cpp#L112
https://github.com/libgeos/geos/blob/3.13.0/src/io/GeoJSONWriter.cpp#L118
All other scalar types will detect the parent node is object or array.
If the parent is object then use key to add child value, else use …
> Fix bug of GeoJSONWriter when there are sub-objects or sub-array in an array

- benchmarks/operation/CMakeLists.txt
- benchmarks/operation/CoverageUnionPerfTest.cpp
- include/geos/geom/GeometryCollection.h
- src/geom/GeometryCollection.cpp
As discussed in https://github.com/locationtech/jts/issues/1100. For a collection with 1 million elements, reduces CoverageUnion runtime by 98%.
Increases the size of collections from 88 to 96 bytes. This could be avoided by storing the flags in `Geometry` (which has 4 spare bytes) rather than `GeometryCollection` (which has none).
This PR:
```
----------------------------------------------------------------------------------
Benchmark                                        Time             CPU   Iterations
----------------------------------------------------------------------------------
BM_CoverageUnion<SegmentSet>/1000          1309915 ns      1309904 ns          544
BM_CoverageUnion<SegmentSet>/4096          5467171 ns      5466976 ns          124
BM_CoverageUnion<SegmentSet>/32768 …
```
> GeometryCollection: Cache flags to avoid O(n) lookups

- src/algorithm/construct/MaximumInscribedCircle.cpp
- tests/unit/algorithm/construct/MaximumInscribedCircleTest.cpp
Fix a bug in `MaximumInscribedCircle` that gives a bad result
```
import shapely, shapely.constructive
import numpy as np
poly = shapely.from_geojson('{"type":"Polygon","coordinates":[[[0.0,-10.0],[-7.07107,-7.07107],[-10.0,0.0],[-7.07107,7.07107],[0.0,10.0],[7.07107,7.07107],[10.0,0.0],[7.07107,-7.07107],[0.0,-10.0]]]}')
u = shapely.constructive.maximum_inscribed_circle(poly, tolerance=0.1)
a, b = np.array(u.coords)
print(a,b,np.linalg.norm(a-b))
```
Actual: 
`[0.       3.535535] [-2.28553181  9.05330273] 5.972387826209451`
Expected:
`[0. 0.] [ 8.53553655 -3.53553126] 9.238796754579768`
> Fix inscribed circle initialization

- src/operation/overlayng/CoverageUnion.cpp
- tests/unit/operation/overlayng/CoverageUnionNGTest.cpp
This resolves an invalid value message shown in shapely:
```pycon
>>> import shapely
>>> shapely.geos_version_string
'3.13.0'
>>> shapely.coverage_union_all([])
/home/mtoews/src/shapely/shapely/shapely/set_operations.py:505: RuntimeWarning: invalid value encountered in coverage_union
return lib.coverage_union(collections, **kwargs)
<GEOMETRYCOLLECTION EMPTY>
```
This is caused by a division by zero in GEOS' `CoverageUnion::geomunion()` with coverage inputs that are empty or don't have an area.
[Tests 9 to 14](https://github.com/libgeos/geos/blob/3.13.0/tests/unit/operation/overlayng/CoverageUnionNGTest.cpp#L141-L205) were silently throwing this warning too, as these input coverages don't have an area.
> Fix invalid values from CoverageUnionNG

- include/geos/geom/HeuristicOverlay.h
- src/geom/Geometry.cpp
- src/geom/HeuristicOverlay.cpp
- src/operation/union/CascadedPolygonUnion.cpp
- src/operation/valid/MakeValid.cpp
- tests/unit/geom/HeuristicOverlayTest.cpp
- tests/xmltester/BufferResultMatcher.cpp
- tests/xmltester/XMLTester.cpp
- tests/xmltester/tests/general/TestOverlayEmpty.xml
This fixes the behaviour of the "combine disjoint" overlay heuristic for GeometryCollections containing empty elements (which are now removed).   
Fixes #1224 
(Note: part of #1224 requires #1136 to be fixed as well).
The PR also:
* centralizes overlay heuristic logic in `HeuristicOverlay` (moving code from `Geometry`)
* modularizes the `HeuristicOverlay` code
* improves `HeuristicOverlay` semantics to return empty results as an empty typed atomic geometry instead of an empty GeometryCollection (this matches `OverlayNG`)
* removes unnecessary dependencies on `HeuristicOverlay` (by calling `OverlayNGRobust` directly where it is known the heuristics do not apply)
* fixes `XMLTester` to correctly handle operation A & B argument switching
> Fix overlay heuristic for GeometryCollections with empty elements

- capi/geos_c.cpp
- capi/geos_c.h.in
- capi/geos_ts_c.cpp
- tests/unit/capi/GEOSClusterTest.cpp
This PR resurrects the C API that was removed from  #688 and changes it to return an array of cluster IDs instead of a GeometryCollection, as suggested in #823.
This is clearly a more flexible API than the one implemented in e464b798a6f6bb04f5de2bd0909ac3a7c4530754, but it becomes somewhat awkward to construct geometries representing the clusters (see function `construct_clusters` in the test suite).
I am a bit averse to adding new types to the C API, but I am wondering if something like the following would be an improvement.
```
struct GEOSClusterInfo;
// return cluster info or NULL on error
GEOSClusterInfo* GEOSClusterDBSCAN(const GEOSGeometry* g, double eps, unsigned minPoints);
unsigned GEOSClusterInfo_getNumClusters(const GEOSClusterInfo* clusters);
unsigned …
```
> Add clustering functions to C API

- tests/xmltester/XMLTester.cpp
- tests/xmltester/XMLTester.h
Improves `XMLTester` by modularizing it using an additional `Test` class and a few lambda functions.  This allows factoring out common code to achieve DRY.
* improves maintainability
* easier to add new operations
* reduces risk of ops missing expected behaviour (e.g. swapping A and B args, test reporting)
* reduces code size (> 800 lines removed)
* adds test file line number reporting
This has also uncovered some issues with result testing (in particular, using topological rather than exact equals).  Fixing this requires fixing a few tests, so will be done in a subsequent PR.
> Refactor XMLTester

- include/geos/algorithm/CGAlgorithmsDD.h
This PR is separated out of #1162 . It contains two changes to the orientation predicate. 
The first change changes the relative error bound from currently 1e-15 to ~3.33e-16, which is proven to be sufficient in https://doi.org/10.1007/s10543-015-0574-9 by Ozaki et al. A tighter error bound can reduce the calls to the expensive exact computation in some degenerate cases (Edit: Here is a gist demonstrating this for a sequence of 100k generated near-collinear inputs https://gist.github.com/tinko92/ce44f93d8d4e4d5909310c00cf19b391 ) and has no disadvantages.
The second changes is also motivated by https://doi.org/10.1007/s10543-015-0574-9 and reduces the number of branches and instructions in the evaluation. This is more concise and may result in faster evaluation (benchmarks are in the …
> Use Ozaki et al.'s error bound and single-branch evaluation in orientation index filter.

- include/geos/operation/buffer/BufferCurveSetBuilder.h
- src/operation/buffer/BufferCurveSetBuilder.cpp
- tests/unit/operation/buffer/BufferOpTest.cpp
Applies the hole erosion heuristic from https://github.com/locationtech/jts/pull/706 to the inside offset curve of buffers of linear rings.  Port of https://github.com/locationtech/jts/pull/1117.
Fixes #1223
```
LINESTRING(25 44, 31 44, 32 38, 29 37, 25 37, 25 38, 24 40, 24 44, 25 44)
```
> Use buffer hole erosion heuristic for rings

- util/CMakeLists.txt
- util/OrientationIndexViewer.cpp
The **Point-Line Orientation geometric predicate** is probably the most crucial algorithm in GEOS, since it is used in many other algorithms, and is notorious for causing [robustness](https://www.cs.cmu.edu/~quake/robust.html) problems.  GEOS has a high-quality implementation which continues to be improved (e.g. see #1184).
Even with a state-of-the-art robust implementation, the orientation predicate behaviour for floating-point inputs can be puzzling (e.g. see #1207, and extensive discussion on #1184).  To assist in understanding its characteristics, and to allow confirming expected behaviour, this PR provides a utility to compute the orientation index for particular cases, and to visualize its behaviour.
```
GEOS Orientation Index Viewer
Usage: orientview [ flags ] x0 y0 x1 y1 x2 y2
-f …
```
> Add Orientation Index Viewer utility

- benchmarks/algorithm/CMakeLists.txt
- benchmarks/algorithm/OrientationIndexStressTest.cpp
Adds an Orientation Index stress test, to test the consistency of the robust Orientation Index algorithm in [`CGAlgorithmsDD::orientationIndex`](https://github.com/libgeos/geos/blob/main/src/algorithm/CGAlgorithmsDD.cpp#L54).
This is a followup to the [discussion](https://github.com/libgeos/geos/pull/1184#issuecomment-2634312584) on #1184.
Orientation Index computation consistency is tested by checking:
* all 3 permutations of input points have same index 
* all 3 permutations of input points in reverse orientation have same index
* orientation index and reverse index have opposite sign, or are collinear
Two ways of generating test cases are provided:
Sample output:
```
DD: 000 000      FP: 000 000         LINESTRING ( 2 0, 0 2 )  - POINT ( 0 2 )
DD: +++ ---      FP: ++0 0--  <! …
```
> Add Orientation Index stress test

- .github/workflows/ci.yml
This CI workaround (bb2db233eb2d51ba1f44cfaaf5dbd39f0cb1af87) is resolved upstream.
> ci: remove workaround for ubuntu-22.04 image with clang++-14

- NEWS.md
- src/geom/CoordinateSequence.cpp
- tests/unit/capi/GEOSCoordSeqTest.cpp
As discussed in https://github.com/libgeos/geos/issues/1244#issuecomment-2683808208
Mixed feelings about this, since the ability to set a Z value on an XY sequence without getting an error has existed since forever.
> CoordinateSequence: Raise error on invalid ordinateIndex

- src/triangulate/quadedge/TrianglePredicate.cpp
This PR is edited to separate out the change to the orientation filter, now in #1184 .
For the incircle predicate, this PR proposes to not generally use long double (which increases precision a little but is not robust as the code notes) but to use a similar error bound filter instead (bound computation based on https://doi.org/10.1007/s10543-023-00975-x , I don't know the source for alternative expression of the incircle determinant, I have first seen it in CGAL). The rational for that is higher performance (roughly 4-10% speedup on my machine for perf_voronoi) and that a more robust computation here is probably motivated by preventing infinite loops in Delaunay Triangulation due to false cases of INTERIOR, which should be impossible with this version (except possibly for inputs near the …
> Use error bound filter in isInCircle predicate instead of long double.

- capi/geos_ts_c.cpp
These two functions only worked when called with LineString, now they also work with CircularString and LinearRing.
> Accepts SimpleCurve geometries in GEOSGeomGetStartPoint_r and mGetEndPoint_r

- include/geos/operation/overlayng/InputGeometry.h
- include/geos/operation/overlayng/OverlayUtil.h
- src/geom/HeuristicOverlay.cpp
- src/operation/overlayng/InputGeometry.cpp
- src/operation/overlayng/OverlayNG.cpp
- src/operation/overlayng/OverlayPoints.cpp
- src/operation/overlayng/OverlayUtil.cpp
- tests/unit/operation/overlayng/OverlayNGEmptyCoordDimTest.cpp
This fixes the OverlayNG semantics for computing the coordinate dimension when overlaying EMPTY geometries, and GEOMETRYCOLLECTIONs with EMPTY elements.
Coordinate dimensions supported are 2 (XY), 3 (XYZ or XYM) and 4 (XYZM).  The semantic used is that the coordinate dimension of an overlay result is the smallest of the coordinate dimensions of the inputs.
Fixs #1248
> Fix OverlayNG coordinate dimemsion handling for EMPTY geometries

- DEVELOPER-NOTES.md
- NEWS.md
- Spelling
- Minor grammar
- A few trailing spaces removed
> DEVELOPER-NOTES.md and NEWS.md: Minor cleanup.

- capi/geos_c.cpp
- capi/geos_c.h.in
- capi/geos_ts_c.cpp
- src/geom/CoordinateSequence.cpp
- tests/unit/capi/GEOSCoordSeqTest.cpp
Also contains a missing `GEOS_COORDSEQ_PADZ` case in one of the CoordSequence constructor.
> Add GEOSCoordSeq_hasZ and GEOSCoordSeq_hasM

- include/geos/io/GeoJSONWriter.h
- src/io/GeoJSONWriter.cpp
- tests/unit/io/GeoJSONWriterTest.cpp
Add a `setForceCCW` function to `GeoJSONWriter`, which enables conversion of polygons to follow the RFC 7946 winding order. When `isForceCCW` is true, linear rings in Polygons and MultiPolygons follow the right-hand rule, meaning exterior rings are counterclockwise, and holes are clockwise.
See https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.6
This addition to GEOS is inspired by a corresponding change in JTS, see https://github.com/locationtech/jts/pull/694
> Allow GeoJSONWriter to force polygons to be counterclockwise

- CMakeLists.txt
- NEWS.md
Analog of https://github.com/OSGeo/gdal/pull/12217
Lets one build GDAL (or anything else) by setting `GEOS_DIR` to a build tree.
> CMake: Create targets file in build tree

- util/geosop/GeometryOp.cpp
Add geosop operation "bufferSingleSided" to enable the parameter [`setSingleSided( true )`](https://libgeos.org/doxygen/classgeos_1_1operation_1_1buffer_1_1BufferOp.html#aaa8c47fc49faef0cafeb3865d8785f31).
For example: `geosop -a "LineString(0 0, 0 1, 1 1, 0 0)" bufferSingleSided 0.2`
> geosop: add bufferSingleSided operation

- tests/unit/CMakeLists.txt
- tests/unit/utility.h
With c++17 or later, `std::filesystem` should normally be enabled, unless the compiler can't compile it.
Setting (e.g.) `-DCMAKE_CXX_STANDARD=11` will disable use of `std::filesystem`.
Not tested with conda-forge/osx_64 to check [this behaviour](https://conda-forge.org/docs/maintainer/knowledge_base/#newer-c-features-with-old-sdk), but hopefully it gets caught.
Closes #1299
> Add CMake check for std::filesystem availability
