libgeos/geos

NEWS
capi/geos_c.cpp
capi/geos_c.h.in
capi/geos_ts_c.cpp
tests/unit/Makefile.am
tests/unit/capi/GEOSGeom_extentTest.cpp

Trac: https://trac.osgeo.org/geos/ticket/871

Add GEOSGeom_getXMin and friends

---

src/index/strtree/AbstractSTRtree.cpp
tests/unit/capi/GEOSSTRtreeTest.cpp

Avoid segfault when querying empty tree

---

src/algorithm/locate/IndexedPointInAreaLocator.cpp
src/index/intervalrtree/SortedPackedIntervalRTree.cpp
src/index/strtree/BoundablePair.cpp
src/triangulate/quadedge/QuadEdgeSubdivision.cpp

I noticed one case of this by chance and found a few more with grep.

Avoid throwing exceptions as pointers

---

src/noding/GeometryNoder.cpp

Reference: https://trac.osgeo.org/geos/ticket/923

Fix memory leak in getNoded

---

include/geos/index/strtree/SIRtree.h
src/index/strtree/SIRtree.cpp
tests/unit/Makefile.am
tests/unit/index/strtree/SIRtreeTest.cpp

Resolves https://trac.osgeo.org/geos/ticket/919

Fix memory leak in SIRtree

---

src/algorithm/MCPointInRing.cpp

Remove unneeded heap allocations, manual deletes, and commented-out code.

Tidy MCPointInRing

---

src/operation/polygonize/EdgeRing.cpp

So that the code aligns with the naming (and with jts)

Fixed todo

---

src/algorithm/CGAlgorithmsDD.cpp

This PR adds the code path to use the (already-implemented ) orientationIndex filter. Benchmarked by running `TopologyPreservingSimplifier` on the GADM boundary of Canada; runtime reduced 50% from 443 seconds to 212 seconds. (Takes 193s with previous, non-robust orientationIndex)
@pramsey

Improve orientationIndex performance with fast filter

---

tests/unit/operation/distance/DistanceOpTest.cpp

This PR adds a test case that attempts to reproduce the error reported in https://github.com/Toblerity/Shapely/issues/560. The test case passes, so I am not able to confirm the Shapely bug in GEOS.

Add test case for DistanceOp::closestPoints

---

README.md

This PR updates the README to provide a bit more background on the project and describe the differences between the C and C++ APIs.

Some updates to README

---

src/noding/ScaledNoder.cpp

This addresses a FIXME that I accidentally introduced recently, and handles a longstanding TODO in the process.

Fix handling of repeated points in ScaledNoder

---

include/geos/operation/valid/RepeatedPointRemover.h

Fix @dbaston 's questionable behaviour 🤣

Add GEOS_DLL missing from class RepeatedPointRemover

---

.codecov.yml
.travis.yml
CMakeLists.txt
tools/ci/script_cmake.sh

This PR attempts to collect code coverage info from one of the Travis runs and report it to codecov, e.g. https://codecov.io/gh/libgeos/geos/tree/2084a8033f1644460bc832b84e3a3d30174658ce

Report code coverage from Travis

---

include/geos/operation/predicate/SegmentIntersectionTester.h
src/algorithm/LineIntersector.cpp
src/geom/CoordinateSequence.cpp
src/geom/prep/PreparedLineStringIntersects.cpp
src/operation/distance/FacetSequence.cpp
src/operation/intersection/RectangleIntersectionBuilder.cpp
src/operation/overlay/PolygonBuilder.cpp
src/operation/polygonize/EdgeRing.cpp
src/operation/predicate/SegmentIntersectionTester.cpp
src/precision/PrecisionReducerCoordinateOperation.cpp
src/precision/SimpleGeometryPrecisionReducer.cpp

Located using a quick check of `egrep -Rn "Coordinate .*="`

Remove some unnecessary Coordinate copies

---

include/geos/geomgraph/GeometryGraph.h
include/geos/geomgraph/index/SimpleMCSweepLineIntersector.h
include/geos/geomgraph/index/SweepLineEvent.h
src/geomgraph/GeometryGraph.cpp
src/geomgraph/index/SimpleMCSweepLineIntersector.cpp
src/geomgraph/index/SweepLineEvent.cpp
src/operation/overlay/OverlayOp.cpp
src/operation/valid/IsValidOp.cpp
tests/unit/operation/IsSimpleOpTest.cpp

https://trac.osgeo.org/geos/ticket/858

Fix invalid read in IsValidOp

---

include/geos/geom/GeometryFactory.h
src/geom/GeometryFactory.cpp

Small change to remove an unnecessary heap allocation / manual delete.

Store PrecisionModel as a value

---

src/algorithm/Distance.cpp
tests/unit/operation/distance/DistanceOpTest.cpp

Trac https://trac.osgeo.org/geos/ticket/584
JTS https://sourceforge.net/p/jts-topo-suite/code/652

Add envelope test to Distance::segmentToSegment

---

include/geos/algorithm/CentralEndpointIntersector.h
include/geos/algorithm/distance/DiscreteFrechetDistance.h
include/geos/algorithm/distance/DiscreteHausdorffDistance.h
include/geos/algorithm/distance/PointPairDistance.h
include/geos/geom/Coordinate.h
include/geos/geom/Coordinate.inl

This can be used to shave some time off minimum distance calculations.
Shaves about 10% off the test suite time for me.

Add Coordinate::distanceSquared

---

include/geos/operation/union/OverlapUnion.h
src/operation/union/OverlapUnion.cpp

As suggested by @dbaston for performance purposes #waronthestack

Allocate linesegments on stack for union check

---

include/geos/geom/MultiLineString.h
include/geos/geom/MultiPoint.h
include/geos/geom/MultiPolygon.h
src/algorithm/PointLocator.cpp
src/geom/MultiLineString.cpp
src/geom/MultiPoint.cpp
src/geom/MultiPolygon.cpp
src/geom/util/GeometryTransformer.cpp
src/io/WKTWriter.cpp
src/operation/IsSimpleOp.cpp
src/operation/intersection/RectangleIntersection.cpp
src/operation/linemerge/LineSequencer.cpp
src/operation/valid/ConnectedInteriorTester.cpp
src/operation/valid/IsValidOp.cpp
src/operation/valid/MakeValid.cpp
src/operation/valid/RepeatedPointTester.cpp

Allows a bunch of call-site casts to be removed.

Return specific type from getGeometryN methods

---

include/geos/index/intervalrtree/SortedPackedIntervalRTree.h
src/algorithm/locate/IndexedPointInAreaLocator.cpp
src/index/intervalrtree/SortedPackedIntervalRTree.cpp

A few low-level changes that are surprisingly significant. Performance gains of 25-35% in my benchmark.

Improve performance of GEOSPreparedContains

---

include/geos/geom/CoordinateArraySequenceFactory.inl
include/geos/geom/LineString.h
src/geom/CoordinateArraySequenceFactory.cpp
src/geom/LineString.cpp
tests/unit/geom/CoordinateArraySequenceFactoryTest.cpp

To have a vtable we should have explicit definition of key function. Details: https://lld.llvm.org/missingkeyfunction.html#missing-key-function

Fixed #285 and https://trac.osgeo.org/geos/ticket/894

---

include/geos/operation/buffer/OffsetSegmentGenerator.h
src/operation/buffer/OffsetSegmentGenerator.cpp
tests/unit/operation/buffer/BufferOpTest.cpp

https:/trac.osgeo.org/geos/ticket/743
References #282

Fix buffer fillet generation to avoid extra segments (JTS-526)

---

CMakeLists.txt

Avoid multiple definitions if shared and inline with MinGW
closes https://github.com/libgeos/geos/issues/288

fix multiple definitions with MinGW

---

include/geos/math/DD.h

MSVC likes explicit export declarations, perhaps this helps

MSVC Build with DD friend operators is not linking

---

tests/unit/capi/GEOSBoundaryTest.cpp
tests/unit/capi/GEOSEnvelopeTest.cpp
tests/unit/capi/GEOSGeom_createLineStringTest.cpp
tests/unit/capi/GEOSGeom_getCoordSeqTest.cpp
tests/unit/capi/GEOSGeom_getCoordinateDimensionTest.cpp
tests/unit/capi/GEOSGeom_getDimensionsTest.cpp
tests/unit/capi/GEOSGetNumInteriorRingsTest.cpp
tests/unit/capi/GEOSLengthTest.cpp
tests/unit/capi/GEOSSetSRIDTest.cpp
tests/unit/capi/GEOSUnionTest.cpp
tests/unit/capi/GEOSisValidReasonTest.cpp
tests/unit/capi/GEOSisValidTest.cpp
tests/unit/capi/capi_test_utils.h

Lost commits discovered when switching to new laptop...

Add some tests for C API functions

---

capi/geos_ts_c.cpp
include/geos/geom/GeometryFactory.inl
include/geos/geom/PrecisionModel.inl
include/geos/io/ByteOrderDataInStream.h
include/geos/io/ByteOrderDataInStream.inl
include/geos/io/WKBReader.h
src/geom/GeometryFactory.cpp
src/geom/PrecisionModel.cpp
src/io/WKBReader.cpp

Improves performance by factor of > 2

Use char array instead of std::istream in WKBReader

---

macros/geos.m4

Add GEOS_CC_LIBS for linking with c++

---

CMakeLists.txt

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

CMakeLists.txt: add BUILD_BENCHMARKS

---

INSTALL

autotools configuration was already removed in 29802a665505aa5fa00f942754d6d16ddfed5823

Remove autotools configuration instructions

---

CMakeLists.txt
src/io/WKBReader.cpp
tests/unit/algorithm/RobustLineIntersectorZTest.cpp
util/geosop/GeosOp.cpp
util/geosop/WKBStreamReader.cpp
util/geosop/WKTStreamReader.cpp

This will no doubt cause some annoyance, but I think it's worth trying as an alternative to scattered efforts to clean these up after the fact.

Treat warnings as errors

---

benchmarks/algorithm/CMakeLists.txt
benchmarks/algorithm/LineIntersectorPerfTest.cpp
benchmarks/algorithm/OrientationIndexPerfTest.cpp
benchmarks/algorithm/locate/CMakeLists.txt
benchmarks/algorithm/locate/IndexedPointInAreaLocatorPerfTest.cpp
benchmarks/geom/CMakeLists.txt
benchmarks/geom/EnvelopePerfTest.cpp
benchmarks/index/CMakeLists.txt
benchmarks/index/chain/CMakeLists.txt
benchmarks/index/chain/MonotoneChainBuilderPerfTest.cpp
benchmarks/index/chain/MonotoneChainPerfTest.cpp
include/geos/algorithm/LineIntersector.inl
include/geos/geom/Envelope.inl
include/geos/geom/util/Densifier.h
include/geos/index/chain/MonotoneChain.h
include/geos/index/chain/MonotoneChainBuilder.h
src/algorithm/LineIntersector.cpp
src/geom/Envelope.cpp
src/index/chain/MonotoneChain.cpp
src/index/chain/MonotoneChainBuilder.cpp

Benchmarks are conditionally enabled if the Google Benchmark library is available. That library seems to do a nice job with reasonably reproducible timings, repeating the code under test enough times until the measurements stabilize.
Also make some minor optimizations identified with the benchmarks.

Add some benchmarks

---

capi/geos_c.h.in
tests/unit/capi/GEOSSTRtreeTest.cpp

Document and test ownership semantics of GEOSSTRtree_insert

---

util/geosop/GeomFunction.cpp

See https://lists.osgeo.org/pipermail/postgis-devel/2021-April/028896.html

Specify full namespace for MSVC C++20

---

src/operation/buffer/OffsetCurveSetBuilder.cpp
tests/unit/capi/GEOSMakeValidTest.cpp
tests/unit/capi/GEOSSTRtreeTest.cpp
tests/unit/operation/buffer/BufferOpTest.cpp

The first commit is a fix in the library itself. Might be backported. Alongside the second commit that is in the test suite.
The third commit is just for master.

Fix memory leaks

---

src/geom/Geometry.cpp
tests/unit/algorithm/CentroidTest.cpp
tests/unit/geom/Geometry/getCentroidTest.cpp
tests/unit/geom/GeometryFactoryTest.cpp
tests/unit/geom/MultiPointTest.cpp
tests/unit/geom/PolygonTest.cpp
tests/xmltester/XMLTester.cpp

https://trac.osgeo.org/geos/ticket/1088

Return POINT EMPTY when centroid called on EMPTY input 

---

include/geos/io/GeoJSON.h
include/geos/io/GeoJSONReader.h
include/geos/io/GeoJSONWriter.h
src/io/GeoJSON.cpp
src/io/GeoJSONReader.cpp
src/io/GeoJSONWriter.cpp

Modify codes of GeoJSON module.
- Make use of right value reference for temp variables;
- Reserve memory of std::vector.

Modify GeoJSON module

---

src/io/GeoJSONWriter.cpp

- Fix bug of wrong index in encodeMultiPolygon. 
- Remove unsed variables.
- Enhance functions by removing temp const reference before returning.

Fix bug in GeoJSON

---

NEWS
src/operation/union/CascadedPolygonUnion.cpp
tests/xmltester/tests/general/TestUnaryUnion.xml

Fix unaryUnion to avoid segfault with empty polygon

---

src/geomgraph/Node.cpp
tests/unit/capi/GEOSPreparedGeometryTest.cpp

Test case to prove the memory leak in #505 on CI systems.

Prepared geometry predicate exception memory leak

---

capi/geos_ts_c.cpp
include/geos/geom/PrecisionModel.h
include/geos/geom/PrecisionModel.inl
src/geom/PrecisionModel.cpp
tests/unit/precision/GeometryPrecisionReducerTest.cpp

Allow specifying a fixed PrecisionModel via grid size

Port https://github.com/locationtech/jts/pull/804

---

src/index/chain/MonotoneChainBuilder.cpp

Avoid constructing a vector whose only purpose is to pass indices
around.

Reduce heap allocations in MonotoneChainBuilder

---

NEWS.md

Hi @pramsey (CC: @jericks, @whuaegeanse, @caspervdw),
I picked your names from the following Git histories or commit message and your GitHub account profiles.
Please check this when you have a time. 🙇‍♂️ 
- https://github.com/libgeos/geos/commits/3.10.0/src/io/GeoJSONReader.cpp
- https://github.com/libgeos/geos/commits/3.10.0/src/io/GeoJSONWriter.cpp
- CAPI: https://github.com/libgeos/geos/commit/b9dc85cd25e8e63bb08f7cfe6c2883440ec232e9
Fixes #535

Added GeoJSON reader/writer support in NEWS.md 3.10.0 section

---

include/geos/index/strtree/TemplateSTRtree.h
tests/unit/capi/GEOSSTRtreeTest.cpp

Fixes https://github.com/libgeos/geos/issues/544

Multiple fixes to STRtree remove method

---

NEWS
include/geos/index/strtree/TemplateSTRtree.h
tests/unit/capi/GEOSSTRtreeTest.cpp

Backport STRtree fix to 3.10

---

capi/geos_c.cpp
capi/geos_c.h.in
capi/geos_ts_c.cpp
tests/unit/capi/GEOSGeom_extentTest.cpp

See discussion in https://github.com/libgeos/geos/pull/554

Add GEOSGeom_getExtent C API function

---

include/geos/index/strtree/TemplateSTRtree.h
tests/unit/index/strtree/TemplateSTRtreeTest.cpp

Contributed by @Ipiano
Resolves https://github.com/libgeos/geos/issues/577

Properly short-circuit STRtree queries

---

.azure-pipelines.yml

Adding a build step to CI pipeline for cross-compilation of `geos` library for windows/arm64 platforms.

add windows/arm64 cross-compilation build to Azure pipeline

---

NEWS.md
src/linearref/LengthLocationMap.cpp
tests/unit/linearref/LengthIndexedLineTest.cpp

Port of fix in https://github.com/locationtech/jts/pull/859.

Fix LengthIndexedLine for touching MultiLineString

---

capi/geos_c.h.in

DOC: add warning to GEOSInterpolate docstring

---

NEWS.md
include/geos/triangulate/polygon/PolygonHoleJoiner.h
src/triangulate/polygon/PolygonHoleJoiner.cpp
tests/unit/triangulate/polygon/ConstrainedDelaunayTriangulatorTest.cpp
tests/unit/triangulate/polygon/PolygonTriangulatorTest.cpp

Fixes `PolygonHoleJoiner`.
See https://github.com/locationtech/jts/pull/862

Fix PolygonHoleJoiner

---

include/geos/algorithm/hull/ConcaveHullOfPolygons.h
include/geos/geom/Envelope.h
include/geos/noding/SegmentExtractingNoder.h
include/geos/triangulate/polygon/ConstrainedDelaunayTriangulator.h
include/geos/triangulate/tri/Tri.h
src/algorithm/hull/ConcaveHullOfPolygons.cpp
src/noding/SegmentExtractingNoder.cpp
src/triangulate/tri/Tri.cpp
tests/unit/algorithm/hull/ConcaveHullOfPolygonsTest.cpp
tests/unit/operation/valid/RepeatedPointRemoverTest.cpp

https://github.com/locationtech/jts/pull/870

Port ConcaveHullOfPolygons from JTS

---

include/geos/algorithm/hull/ConcaveHullOfPolygons.h
src/algorithm/hull/ConcaveHullOfPolygons.cpp
tests/unit/algorithm/hull/ConcaveHullOfPolygonsTest.cpp

Fixes ConcaveHullOfPolygons hole eroding to avoid eroding too much.
See https://github.com/locationtech/jts/pull/887

Fix ConcaveHullOfPolygons hole erosion

---

capi/geos_c.cpp
capi/geos_c.h.in
capi/geos_ts_c.cpp
include/geos/geom/CoordinateSequence.h
include/geos/io/WKBReader.h
include/geos/io/WKTReader.h
src/geom/CoordinateSequence.cpp
src/io/WKBReader.cpp
src/io/WKTReader.cpp
src/operation/buffer/BufferCurveSetBuilder.cpp
tests/unit/capi/GEOSGeomFromWKBTest.cpp
tests/unit/io/WKTReaderTest.cpp

Add setFixStructure() to WKB/WKT readers

---

capi/geos_ts_c.cpp
src/geom/util/GeometryEditor.cpp
tests/unit/capi/GEOSGeom_setPrecisionTest.cpp
tests/unit/geom/GeometryFactoryTest.cpp

Fixes https://trac.osgeo.org/geos/ticket/1137

Fix GeometryPrecisionReducer to return empty 2D polygon from collapsed 2D input

---

.azure-pipelines.yml

Attempt to fix current CI failures for MacOS.

CI: Update MacOS to version 11

---

include/geos/geomgraph/NodeMap.h
include/geos/operation/relate/EdgeEndBuilder.h
include/geos/operation/relate/RelateComputer.h
include/geos/operation/relate/RelateNodeGraph.h
src/geomgraph/Node.cpp
src/geomgraph/NodeMap.cpp
src/operation/relate/EdgeEndBuilder.cpp
src/operation/relate/RelateComputer.cpp
src/operation/relate/RelateNodeGraph.cpp
tests/unit/capi/GEOSUnionTest.cpp

Fixes https://github.com/libgeos/geos/issues/606

Fix double-free when Node::add throws

---

NEWS.md
capi/geos_c.cpp
capi/geos_c.h.in
capi/geos_ts_c.cpp
tests/unit/capi/GEOSLineSubstringTest.cpp
tests/unit/capi/capi_test_utils.h

Resolves https://github.com/libgeos/geos/issues/706

Add GEOSLineSubstring

---

include/geos/io/WKBStreamReader.h
include/geos/io/WKTFileReader.h
include/geos/io/WKTStreamReader.h
src/io/WKBStreamReader.cpp
src/io/WKTFileReader.cpp
src/io/WKTStreamReader.cpp
util/geosop/CMakeLists.txt
util/geosop/GeosOp.cpp

This enables them to be used for performance tests and other utilities

Move readers from geosop into library

---

src/geom/GeometryFactory.cpp
tests/unit/precision/GeometryPrecisionReducerTest.cpp

Fixes https://github.com/libgeos/geos/issues/748

Fix null pointer deref when constructing empty point

---

NEWS.md
src/algorithm/distance/DiscreteFrechetDistance.cpp
tests/unit/algorithm/distance/DiscreteFrechetDistanceTest.cpp

Fixes https://github.com/libgeos/geos/issues/751

Fix DiscreteFrechetDistance crash on empty inputs

---

src/operation/valid/RepeatedPointRemover.cpp
tests/unit/capi/GEOSRemoveRepeatedPointsTest.cpp

Fixes https://github.com/libgeos/geos/issues/759

RepeatedPointRemover: Avoid reading invalidated reference

---

tests/unit/capi/GEOSFrechetDistanceTest.cpp

Confirming past resolution of https://trac.osgeo.org/geos/ticket/1086

Add tests for discrete Frechet distance with tiny dens. frac

---

src/triangulate/VoronoiDiagramBuilder.cpp
tests/unit/triangulate/VoronoiTest.cpp

Fixes https://github.com/libgeos/geos/issues/795

Fix crash on on empty Voronoi diagram

---

NEWS.md
src/operation/union/PointGeometryUnion.cpp
tests/unit/capi/GEOSUnaryUnionTest.cpp

Fixes https://github.com/libgeos/geos/issues/830

Fix crash on GC union with empty points

---

include/geos/index/strtree/TemplateSTRtree.h
tests/unit/capi/GEOSSTRtreeTest.cpp

GEOSSTRtree_iterate: Do not return removed items

---

NEWS.md
src/operation/buffer/BufferCurveSetBuilder.cpp
tests/unit/capi/GEOSBufferTest.cpp

GEOSBuffer: Fix segfault with Inf coords

---

NEWS.md
src/algorithm/distance/DistanceToPoint.cpp
tests/unit/algorithm/distance/DiscreteHausdorffDistanceTest.cpp
util/geosop/GeomFunction.cpp

HausdorffDistance: Fix crash on collection with empty components

---

NEWS.md
capi/geos_c.cpp
capi/geos_c.h.in
capi/geos_ts_c.cpp
tests/unit/capi/GEOSSTRtreeTest.cpp

Also update C API docs to clarify which functions cause a tree to be constructed

C API: Add GEOSSTRtree_build

---

NEWS.md
src/operation/buffer/OffsetCurve.cpp
tests/unit/operation/buffer/OffsetCurveTest.cpp

Fix OffsetCurve to handle zero-distance offset

---

util/geosop/GeomFunction.cpp

I noticed these functions were missing from geosop.
A careful review of my novice C++ would be appreciated.
Other name suggestions are welcome, e.g. `interpolate` vs `extractPoint`.
A `substring`/`extractLine` operator would be nice, but `geosop` is currently limited to one argument, so this presently isn't possible.

Add linear referencing functions "interpolate" and "project" to geosop

---

src/operation/buffer/BufferBuilder.cpp
tests/unit/operation/buffer/BufferOpTest.cpp

Fix single-sided buffer of multigeoms

---

include/geos/geom/Geometry.h
include/geos/geom/HeuristicOverlay.h
src/geom/Geometry.cpp
src/geom/HeuristicOverlay.cpp
tests/unit/geom/DimensionTest.cpp
tests/unit/geom/HeuristicOverlayTest.cpp

A first attempt to address GH-797 with some basic heuristics.

Overlay with mixed dimension

---

NEWS.md
capi/geos_ts_c.cpp
include/geos/geom/CoordinateSequence.h
src/geom/GeometryFactory.cpp
tests/unit/geom/PointTest.cpp
tests/unit/io/GeoJSONWriterTest.cpp
tests/unit/io/WKTReaderTest.cpp
tests/unit/io/WKTWriterTest.cpp

Remove NaN point special case logic

---

NEWS.md
src/io/WKTWriter.cpp
tests/unit/io/GeoJSONReaderTest.cpp
tests/unit/io/WKTWriterTest.cpp

Fix WKTWriter to emit EMPTY elements in multi-geometries

---

src/geom/GeometryFactory.cpp
tests/unit/capi/GEOSGeom_createTest.cpp
tests/unit/capi/GEOSHasZMTest.cpp

Return 2D empty linestring on GEOSGeom_createLineString(NULL)

---

src/algorithm/construct/IndexedDistanceToPoint.cpp
tests/unit/algorithm/construct/LargestEmptyCircleTest.cpp

Fix and test for LargestEmptyCircle crash on malformed input

---

.github/workflows/ci.yml

Some testing of non-Intel architecture...

CI: replace macos-11/xcode 13.2.1 config by ARM64 M1/xcode 14.3

---

.github/workflows/codeql.yml

fixes issues like https://github.com/OSGeo/gdal/actions/runs/8032403542/job/21944690464#step:4:126

codeql.yml: add 'apt-get update'

---

src/algorithm/Centroid.cpp
tests/unit/algorithm/CentroidTest.cpp

Resolves https://github.com/libgeos/geos/issues/1073

Centroid: Avoid crash with empty hole

---

src/precision/MinimumClearance.cpp
tests/unit/capi/GEOSMinimumClearanceTest.cpp

Resolves https://github.com/libgeos/geos/issues/1079

MinimumClearance: Avoid crash on NaN inputs

---

tests/unit/io/WKBWriterTest.cpp

unit-io-WKBWriter: fix test failures on big-endian (s390x)

---

util/geosop/GeosOp.cpp

This shows floating-point exception information with `geosop` in verbose mode.
```bash
$ ./bin/geosop -a "POLYGON EMPTY" -b "POLYGON EMPTY" coverageUnion -v
Input A: WKT literal
Read 1 geometries, 0 vertices  -- 164 usec
Input B: WKT literal
Read 1 geometries, 0 vertices  -- 9 usec
[ 1] coverageUnion: A[1] Polygon( 0 )  -> MultiPolygon( 0 )  --  82 usec
MULTIPOLYGON EMPTY
Operation raised floating-point environment flag(s): FE_INVALID
Ran 1 coverageUnion ops ( 0 vertices)  -- 82 usec    (GEOS 3.14.0dev)
```
It shows most floating-point exception flags except for FE_INEXACT, which is almost always harmless, e.g.<br /> `geosop -v -a "POINT(0 0)" -b "POINT(1 1)" distance` would raise it since the answer is irrational (sqrt(2) = 1.41421...)

geosop: show most floating-point exceptions in verbose mode

---

.github/workflows/ci.yml

Restores uploading to Codecov. Tested on my fork: https://app.codecov.io/gh/dbaston/libgeos/

CI: Use token for codecov upload

---

capi/geos_ts_c.cpp

Add missing cases for GEOS_MULTICURVE and GEOS_MULTISURFACE in GEOSGeom_createEmptyCollection_r

Add missing cases in GEOSGeom_createEmptyCollection_r

---

capi/geos_ts_c.cpp

Forgot that one in the previous PR!

Accept SimpleCurve geometries in GEOSGeomGetPointN_r

---

src/operation/union/UnaryUnionOp.cpp

Not totally sure, but it seems to me the current comment is wrong (and if it is not, something should be better explained :-))

UnaryUnionOp::Union(): fix wrong comment

---

.gitignore
src/operation/distance/DistanceOp.cpp
src/operation/distance/IndexedFacetDistance.cpp

Fix withinDistance with negative distance value.

---

NEWS.md
capi/geos_c.cpp
capi/geos_c.h.in
capi/geos_ts_c.cpp
tests/unit/capi/GEOSisSimpleDetailTest.cpp

As discussed at https://github.com/OSGeo/gdal/pull/12880#discussion_r2270081590

Add GEOSisSimpleDetail
